#!/usr/bin/env python3
"""
SoterAI - MiniLM-L6-v2 ONNX Training Script

Fine-tunes sentence-transformers/all-MiniLM-L6-v2 for text classification
on the adversarial dataset generated by generate-adversarial-dataset.ts,
then exports to ONNX format for in-process inference via onnxruntime-node.

Usage:
    # 1. Install dependencies
    pip install torch transformers datasets onnx onnxruntime sentence-transformers scikit-learn

    # 2. Train (with default dataset paths)
    python scripts/ml/train-onnx-model.py

    # 3. Train with custom data / config
    python scripts/ml/train-onnx-model.py \
        --train-datasets datasets/ml-adversarial-combined.jsonl \
        --val-split 0.15 \
        --epochs 5 \
        --batch-size 16 \
        --lr 2e-5 \
        --output-dir models/ml-classifier-v1

    # 4. Quick test run with just 100 samples
    python scripts/ml/train-onnx-model.py --sample

Output:
    models/ml-classifier-v1/
    ├── model.onnx           # The exported ONNX model
    ├── labels.json          # Label index → name mapping
    ├── training_stats.json  # Training history
    ├── eval_results.json    # Final evaluation metrics
    └── tokenizer_config/    # Tokenizer files for the Node.js wrapper

The ONNX model outputs raw logits. Apply softmax in the Node.js inference
code (lib/ml/onnxBackend.ts) to convert to probabilities.
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModel
from torch.optim import AdamW
from transformers import get_linear_schedule_with_warmup
from sklearn.metrics import classification_report, f1_score
import onnx
import onnxruntime


# ── Constants ──────────────────────────────────────────────────────────────────

MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIM = 384  # MiniLM-L6-v2 output dimension

# Label mapping — must match the MLLabel type from lib/ml/types.ts
ALL_LABELS = [
    "SAFE",
    "PROMPT_INJECTION",
    "JAILBREAK",
    "SYSTEM_PROMPT_LEAK_ATTEMPT",
    "PII",
    "SECRET",
    "UNSAFE_OUTPUT",
    "RAG_POISONING",
    "DATA_EXFILTRATION_ATTEMPT",
]

DEFAULT_DATASETS = [
    "datasets/ml-adversarial-combined.jsonl",
    "datasets/ml-adversarial-training.jsonl",
]

# ── Dataset ────────────────────────────────────────────────────────────────────


class AdversarialDataset(Dataset):
    """Loads JSONL files containing {'text': ..., 'label': ...} rows."""

    def __init__(self, file_paths: list[str], label_to_idx: dict[str, int], max_samples: int | None = None):
        self.texts: list[str] = []
        self.labels: list[int] = []
        self.label_to_idx = label_to_idx

        for fp in file_paths:
            path = Path(fp)
            if not path.exists():
                print(f"  [WARN] Skipping {fp} — file not found")
                continue
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                        text = obj.get("text", "")
                        label_str = obj.get("label", "SAFE")
                        if not text:
                            continue
                        # Map label string to index
                        label_idx = label_to_idx.get(label_str)
                        if label_idx is None:
                            # Fallback: try case-insensitive
                            for k, v in label_to_idx.items():
                                if k.upper() == label_str.upper():
                                    label_idx = v
                                    break
                        if label_idx is None:
                            print(f"  [WARN] Unknown label '{label_str}', skipping row")
                            continue
                        self.texts.append(text)
                        self.labels.append(label_idx)
                    except json.JSONDecodeError:
                        continue

        if max_samples and len(self.texts) > max_samples:
            # Stratified sampling to preserve class balance
            combined = list(zip(self.texts, self.labels))
            rng = np.random.RandomState(42)
            rng.shuffle(combined)
            combined = combined[:max_samples]
            self.texts, self.labels = zip(*combined)
            self.texts = list(self.texts)
            self.labels = list(self.labels)

        print(f"  [OK] Loaded {len(self.texts)} examples from {len(file_paths)} file(s)")
        self._print_label_distribution()

    def _print_label_distribution(self) -> None:
        idx_to_label = {v: k for k, v in self.label_to_idx.items()}
        counts: dict[str, int] = {}
        for lbl in self.labels:
            name = idx_to_label.get(lbl, f"UNKNOWN_{lbl}")
            counts[name] = counts.get(name, 0) + 1
        for name in sorted(counts.keys()):
            print(f"    {name:40s} {counts[name]:6d} ({counts[name]/len(self.labels)*100:5.1f}%)")

    def __len__(self) -> int:
        return len(self.texts)

    def __getitem__(self, idx: int) -> tuple[str, int]:
        return self.texts[idx], self.labels[idx]


# ── Model ──────────────────────────────────────────────────────────────────────


class MiniLMClassifier(nn.Module):
    """
    MiniLM-L6-v2 with a classification head.

    Architecture:
        1. Transformer encoder (MiniLM-L6) with mean pooling
        2. Dropout for regularization
        3. Linear projection to num_labels

    Input: tokenizer output dict with input_ids, attention_mask
    Output: raw logits (no softmax)
    """

    def __init__(self, num_labels: int, dropout: float = 0.1):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(MODEL_NAME)
        self.dropout = nn.Dropout(dropout)
        self.classifier = nn.Linear(EMBEDDING_DIM, num_labels)

    def forward(
        self, input_ids: torch.Tensor, attention_mask: torch.Tensor
    ) -> torch.Tensor:
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        # Mean pooling over token embeddings, masked by attention_mask
        token_embeddings = outputs.last_hidden_state  # (batch, seq, 384)
        input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
        sum_embeddings = torch.sum(token_embeddings * input_mask_expanded, dim=1)
        sum_mask = torch.clamp(input_mask_expanded.sum(dim=1), min=1e-9)
        pooled = sum_embeddings / sum_mask  # (batch, 384)
        pooled = self.dropout(pooled)
        logits = self.classifier(pooled)  # (batch, num_labels)
        return logits


# ── Collation ──────────────────────────────────────────────────────────────────


def collate_fn(
    batch: list[tuple[str, int]], tokenizer, max_length: int = 128
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Tokenize a batch of (text, label) pairs and return model inputs."""
    texts = [item[0] for item in batch]
    labels = [item[1] for item in batch]

    encoded = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )

    return encoded["input_ids"], encoded["attention_mask"], torch.tensor(labels, dtype=torch.long)


# ── Training ────────────────────────────────────────────────────────────────────


def train_epoch(
    model: MiniLMClassifier,
    dataloader: DataLoader,
    optimizer: torch.optim.Optimizer,
    scheduler,
    device: torch.device,
) -> dict:
    """Train for one epoch. Returns average loss and per-label metrics."""
    model.train()
    total_loss = 0.0
    all_preds: list[int] = []
    all_labels: list[int] = []
    step = 0

    for input_ids, attention_mask, labels in dataloader:
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        logits = model(input_ids, attention_mask)
        loss = nn.CrossEntropyLoss()(logits, labels)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        preds = torch.argmax(logits, dim=1)
        all_preds.extend(preds.cpu().tolist())
        all_labels.extend(labels.cpu().tolist())
        step += 1

    avg_loss = total_loss / max(1, step)
    f1 = f1_score(all_labels, all_preds, average="weighted", zero_division=0)

    return {"loss": avg_loss, "f1": f1, "predictions": all_preds, "labels": all_labels}


@torch.no_grad()
def evaluate(
    model: MiniLMClassifier,
    dataloader: DataLoader,
    device: torch.device,
    label_names: list[str],
) -> dict:
    """Evaluate model on a dataloader. Returns loss, accuracy, F1, and report."""
    model.eval()
    total_loss = 0.0
    all_preds: list[int] = []
    all_labels: list[int] = []
    all_probs: list[list[float]] = []
    step = 0

    for input_ids, attention_mask, labels in dataloader:
        input_ids = input_ids.to(device)
        attention_mask = attention_mask.to(device)
        labels = labels.to(device)

        logits = model(input_ids, attention_mask)
        loss = nn.CrossEntropyLoss()(logits, labels)
        total_loss += loss.item()

        probs = torch.softmax(logits, dim=1)
        preds = torch.argmax(logits, dim=1)

        all_preds.extend(preds.cpu().tolist())
        all_labels.extend(labels.cpu().tolist())
        all_probs.extend(probs.cpu().tolist())
        step += 1

    avg_loss = total_loss / max(1, step)
    accuracy = sum(1 for p, l in zip(all_preds, all_labels) if p == l) / max(1, len(all_preds))
    f1_macro = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    f1_weighted = f1_score(all_labels, all_preds, average="weighted", zero_division=0)

    # Explicitly pass labels so classification_report knows all expected classes
    # even if some don't appear in the validation batch.
    all_expected = list(range(len(label_names)))
    report = classification_report(
        all_labels,
        all_preds,
        labels=all_expected,
        target_names=label_names,
        zero_division=0,
        output_dict=True,
    )

    return {
        "loss": avg_loss,
        "accuracy": accuracy,
        "f1_macro": f1_macro,
        "f1_weighted": f1_weighted,
        "classification_report": report,
        "predictions": all_preds,
        "labels": all_labels,
        "probabilities": all_probs,
    }


# ── ONNX Export ────────────────────────────────────────────────────────────────


def export_to_onnx(
    model: MiniLMClassifier,
    tokenizer,
    output_dir: str,
    model_name: str = "model.onnx",
) -> str:
    """
    Export the trained model to ONNX format with dynamic axes
    for variable batch size and sequence length.

    Returns: path to the exported .onnx file.
    """
    model.eval()
    device = next(model.parameters()).device

    # Create dummy input for tracing
    dummy_text = ["This is a sample input for ONNX tracing purposes."]
    encoded = tokenizer(dummy_text, return_tensors="pt")
    dummy_input_ids = encoded["input_ids"].to(device)
    dummy_attention_mask = encoded["attention_mask"].to(device)

    output_path = os.path.join(output_dir, model_name)

    # Export to ONNX
    torch.onnx.export(
        model,
        (dummy_input_ids, dummy_attention_mask),
        output_path,
        input_names=["input_ids", "attention_mask"],
        output_names=["logits"],
        dynamic_axes={
            "input_ids": {0: "batch_size", 1: "sequence_length"},
            "attention_mask": {0: "batch_size", 1: "sequence_length"},
            "logits": {0: "batch_size"},
        },
        opset_version=14,
        do_constant_folding=True,
    )

    # Validate the exported model
    onnx_model = onnx.load(output_path)
    onnx.checker.check_model(onnx_model)
    print(f"  [OK] ONNX model validated: {output_path}")

    # Test inference with onnxruntime
    ort_session = onnxruntime.InferenceSession(output_path)
    ort_inputs = {
        "input_ids": dummy_input_ids.cpu().numpy(),
        "attention_mask": dummy_attention_mask.cpu().numpy(),
    }
    ort_outputs = ort_session.run(None, ort_inputs)
    print(f"  [OK] ONNX inference test: output shape {ort_outputs[0].shape}")

    return output_path


# ── Label mapping ──────────────────────────────────────────────────────────────


def save_label_mapping(output_dir: str, label_names: list[str]) -> str:
    """Save label index → name mapping as JSON."""
    mapping = {str(i): name for i, name in enumerate(label_names)}
    path = os.path.join(output_dir, "labels.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(mapping, f, indent=2)
    print(f"  [OK] Saved label mapping ({len(mapping)} labels) to {path}")
    return path


def save_tokenizer(output_dir: str, tokenizer) -> str:
    """Save tokenizer so Node.js wrapper can load it."""
    tokenizer_dir = os.path.join(output_dir, "tokenizer_config")
    tokenizer.save_pretrained(tokenizer_dir)
    print(f"  [OK] Saved tokenizer config to {tokenizer_dir}")

    # Also save vocab.txt for Node.js LightweightTokenizer
    vocab = tokenizer.get_vocab()
    sorted_tokens = sorted(vocab.items(), key=lambda x: x[1])  # sort by ID
    vocab_path = os.path.join(tokenizer_dir, "vocab.txt")
    with open(vocab_path, "w", encoding="utf-8") as f:
        for token, _ in sorted_tokens:
            f.write(token + chr(10))
    print(f"  [OK] Saved vocab.txt ({len(sorted_tokens)} tokens) for Node.js tokenizer")
    return tokenizer_dir


# ── Main ────────────────────────────────────────────────────────────────────────


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune MiniLM-L6-v2 for AI security attack classification and export to ONNX"
    )
    parser.add_argument(
        "--train-datasets",
        nargs="+",
        default=None,
        help="JSONL training files (default: finds in datasets/ml-adversarial-*.jsonl)",
    )
    parser.add_argument(
        "--val-split",
        type=float,
        default=0.15,
        help="Fraction of data to use for validation (default: 0.15)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=5,
        help="Number of training epochs (default: 5)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=16,
        help="Training batch size (default: 16)",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=2e-5,
        help="Learning rate (default: 2e-5)",
    )
    parser.add_argument(
        "--max-length",
        type=int,
        default=128,
        help="Maximum tokenization sequence length (default: 128)",
    )
    parser.add_argument(
        "--dropout",
        type=float,
        default=0.1,
        help="Dropout rate on classifier head (default: 0.1)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="models/ml-classifier-v1",
        help="Output directory for model artifacts (default: models/ml-classifier-v1)",
    )
    parser.add_argument(
        "--sample",
        action="store_true",
        help="Quick test with just 100 samples",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed (default: 42)",
    )
    parser.add_argument(
        "--no-cuda",
        action="store_true",
        help="Disable CUDA even if available",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # ── Fix Windows encoding ──────────────────────────────────────────────────
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding="utf-8")
            sys.stderr.reconfigure(encoding="utf-8")
        except AttributeError:
            pass

    # ── Device ────────────────────────────────────────────────────────────────
    if args.no_cuda:
        device = torch.device("cpu")
    else:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n{'=' * 70}")
    print(f"  SoterAI — MiniLM-L6-v2 ONNX Training")
    print(f"  Device: {device}")
    print(f"{'=' * 70}\n")

    # ── Seed ──────────────────────────────────────────────────────────────────
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    # ── Find datasets ──────────────────────────────────────────────────────────
    train_datasets = args.train_datasets
    if not train_datasets:
        train_datasets = []
        for pattern in DEFAULT_DATASETS:
            p = Path(pattern)
            if p.exists():
                train_datasets.append(str(p))
        # Also find any JSONL files in datasets/
        datasets_dir = Path("datasets")
        if datasets_dir.exists():
            for f in sorted(datasets_dir.glob("*.jsonl")):
                fp = str(f)
                if fp not in train_datasets:
                    train_datasets.append(fp)

    if not train_datasets:
        print("[ERROR] No training datasets found. Generate them first:")
        print("   npx tsx scripts/ml/generate-adversarial-dataset.ts")
        print("   Then re-run this script.")
        sys.exit(1)

    print("[INFO] Input datasets:")
    for fp in train_datasets:
        exists = Path(fp).exists()
        print(f"  {'[OK]' if exists else '[MISSING]'} {fp}")

    # ── Label mapping ────────────────────────────────────────────────────────────
    label_to_idx = {name: i for i, name in enumerate(ALL_LABELS)}
    idx_to_label = {i: name for name, i in label_to_idx.items()}
    num_labels = len(ALL_LABELS)
    print(f"\n[INFO] Label schema: {num_labels} labels ({', '.join(ALL_LABELS)})")

    # ── Load dataset ──────────────────────────────────────────────────────────────
    print("\n[INFO] Loading dataset...")
    max_samples = 100 if args.sample else None
    full_dataset = AdversarialDataset(train_datasets, label_to_idx, max_samples=max_samples)

    if len(full_dataset) == 0:
        print("[ERROR] Dataset is empty after loading.")
        sys.exit(1)

    # ── Train/val split ──────────────────────────────────────────────────────────
    val_size = max(1, int(len(full_dataset) * args.val_split))
    train_size = len(full_dataset) - val_size
    train_set, val_set = torch.utils.data.random_split(
        full_dataset, [train_size, val_size],
        generator=torch.Generator().manual_seed(args.seed),
    )
    print(f"\n[INFO] Split: {train_size} train / {val_size} validation")

    # ── Tokenizer ────────────────────────────────────────────────────────────────
    print(f"\n[INFO] Loading tokenizer ({MODEL_NAME})...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    # ── Dataloaders ──────────────────────────────────────────────────────────────
    train_loader = DataLoader(
        train_set,
        batch_size=args.batch_size,
        shuffle=True,
        collate_fn=lambda b: collate_fn(b, tokenizer, args.max_length),
    )
    val_loader = DataLoader(
        val_set,
        batch_size=args.batch_size * 2,
        shuffle=False,
        collate_fn=lambda b: collate_fn(b, tokenizer, args.max_length),
    )

    print(f"  Train batches: {len(train_loader)}")
    print(f"  Val batches:   {len(val_loader)}")

    # ── Model ──────────────────────────────────────────────────────────────────
    print(f"\n[INFO] Initializing model ({MODEL_NAME})...")
    model = MiniLMClassifier(num_labels=num_labels, dropout=args.dropout)
    model.to(device)

    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"  Total parameters: {total_params:,}")
    print(f"  Trainable:        {trainable_params:,}")

    # ── Optimizer & scheduler ──────────────────────────────────────────────────
    num_training_steps = len(train_loader) * args.epochs
    num_warmup_steps = int(num_training_steps * 0.1)

    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=0.01)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=num_training_steps,
    )

    print(f"  Learning rate: {args.lr}")
    print(f"  Batch size:    {args.batch_size}")
    print(f"  Epochs:        {args.epochs}")
    print(f"  Warmup steps:  {num_warmup_steps}")
    print(f"  Total steps:   {num_training_steps}")

    # ── Training loop ────────────────────────────────────────────────────────────
    print(f"\n{'-' * 70}")
    print("  Training")
    print(f"{'-' * 70}\n")

    best_f1 = 0.0
    best_model_path = None
    training_history: list[dict] = []

    for epoch in range(1, args.epochs + 1):
        epoch_start = time.time()

        train_metrics = train_epoch(model, train_loader, optimizer, scheduler, device)
        val_metrics = evaluate(model, val_loader, device, ALL_LABELS)

        epoch_time = time.time() - epoch_start

        # Save best model
        if val_metrics["f1_weighted"] > best_f1:
            best_f1 = val_metrics["f1_weighted"]
            os.makedirs(args.output_dir, exist_ok=True)
            best_model_path = os.path.join(args.output_dir, "pytorch_model.bin")
            torch.save(model.state_dict(), best_model_path)

        record = {
            "epoch": epoch,
            "train_loss": round(train_metrics["loss"], 4),
            "train_f1": round(train_metrics["f1"], 4),
            "val_loss": round(val_metrics["loss"], 4),
            "val_accuracy": round(val_metrics["accuracy"], 4),
            "val_f1_macro": round(val_metrics["f1_macro"], 4),
            "val_f1_weighted": round(val_metrics["f1_weighted"], 4),
            "time_seconds": round(epoch_time, 1),
            "lr": scheduler.get_last_lr()[0] if scheduler.get_last_lr() else args.lr,
        }
        training_history.append(record)

        print(
            f"  Epoch {epoch:2d}/{args.epochs}  "
            f"train_loss={record['train_loss']:.4f}  "
            f"val_loss={record['val_loss']:.4f}  "
            f"val_acc={record['val_accuracy']:.4f}  "
            f"val_f1={record['val_f1_weighted']:.4f}  "
            f"[{record['time_seconds']:.1f}s]"
        )

    # ── Load best model ──────────────────────────────────────────────────────────
    print(f"\n[INFO] Loading best model (val F1={best_f1:.4f})...")
    model.load_state_dict(torch.load(best_model_path, map_location=device))
    model.to(device)

    # ── Final evaluation ──────────────────────────────────────────────────────────
    print("\n[INFO] Final evaluation on validation set...")
    final_metrics = evaluate(model, val_loader, device, ALL_LABELS)

    print(f"\n  -- Final Metrics --")
    print(f"  Loss:           {final_metrics['loss']:.4f}")
    print(f"  Accuracy:       {final_metrics['accuracy']:.4f} ({final_metrics['accuracy']*100:.2f}%)")
    print(f"  F1 (macro):     {final_metrics['f1_macro']:.4f}")
    print(f"  F1 (weighted):  {final_metrics['f1_weighted']:.4f}")

    print(f"\n  -- Per-Label Metrics --")
    report = final_metrics["classification_report"]
    for label_name in ALL_LABELS:
        if label_name in report:
            metrics = report[label_name]
            print(
                f"  {label_name:40s} "
                f"prec={metrics['precision']:.3f}  "
                f"rec={metrics['recall']:.3f}  "
                f"f1={metrics['f1-score']:.3f}  "
                f"support={metrics['support']:4.0f}"
            )

    # ── Export to ONNX ────────────────────────────────────────────────────────────
    print(f"\n{'-' * 70}")
    print("  Exporting to ONNX")
    print(f"{'-' * 70}\n")

    os.makedirs(args.output_dir, exist_ok=True)

    # Move model to CPU for ONNX export
    model.cpu()

    onnx_path = export_to_onnx(model, tokenizer, args.output_dir)
    label_path = save_label_mapping(args.output_dir, ALL_LABELS)
    tokenizer_path = save_tokenizer(args.output_dir, tokenizer)

    # ── Guard: ensure training produced a valid model ────────────────────────────
    if best_model_path is None:
        print("\n[ERROR] Model failed to improve during training (best_f1 == 0.0).")
        print("   Check dataset quality or increase epochs.")
        sys.exit(1)

    # ── Save training stats ──────────────────────────────────────────────────────
    stats_path = os.path.join(args.output_dir, "training_stats.json")
    with open(stats_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "model_name": MODEL_NAME,
                "embedding_dim": EMBEDDING_DIM,
                "num_labels": num_labels,
                "labels": ALL_LABELS,
                "training_args": vars(args),
                "history": training_history,
                "final_metrics": {
                    "loss": final_metrics["loss"],
                    "accuracy": final_metrics["accuracy"],
                    "f1_macro": final_metrics["f1_macro"],
                    "f1_weighted": final_metrics["f1_weighted"],
                },
                "per_label_metrics": {
                    name: report[name]
                    for name in ALL_LABELS
                    if name in report
                },
            },
            f,
            indent=2,
        )
    print(f"\n  [OK] Saved training stats to {stats_path}")

    # ── Save eval results (flat JSON for easy Node.js consumption) ────────────────
    eval_path = os.path.join(args.output_dir, "eval_results.json")
    with open(eval_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "accuracy": final_metrics["accuracy"],
                "f1_macro": final_metrics["f1_macro"],
                "f1_weighted": final_metrics["f1_weighted"],
                "per_label": {
                    name: {
                        "precision": report[name]["precision"],
                        "recall": report[name]["recall"],
                        "f1": report[name]["f1-score"],
                        "support": report[name]["support"],
                    }
                    for name in ALL_LABELS
                    if name in report
                },
            },
            f,
            indent=2,
        )
    print(f"  [OK] Saved eval results to {eval_path}")

    # ── Summary ───────────────────────────────────────────────────────────────────
    print(f"\n{'=' * 70}")
    print(f"  Training Complete")
    print(f"{'=' * 70}")
    print(f"  Best validation F1: {best_f1:.4f}")
    print(f"  ONNX model:         {onnx_path}")
    print(f"  Model size:          {os.path.getsize(onnx_path) / 1024 / 1024:.1f} MB")
    print(f"  Labels:             {label_path}")
    print(f"  Tokenizer:          {tokenizer_path}/")
    print(f"  Training stats:     {stats_path}")
    print()
    print(f"  To use in Node.js:")
    print(f"    const session = await ort.InferenceSession.create('{onnx_path}');")
    print(f"    // Load labels.json for label mapping")
    print(f"{'=' * 70}\n")


if __name__ == "__main__":
    main()
