/**
 * Asserts the TS BertTokenizer (lib/ml/bertTokenizer.ts) produces token ids
 * IDENTICAL to the Python HuggingFace tokenizer the model trained with.
 *
 * Run (after scripts/ml/dump-hf-tokenization.py):
 *   npx tsx scripts/ml/verify-tokenizer-parity.ts
 *   npx tsx scripts/ml/verify-tokenizer-parity.ts --model-dir models/ml-classifier-v17
 *
 * WHY THE OPTIONS ARE READ FROM tokenizer_config.json AND NOT HARDCODED
 *   This file used to construct the tokenizer with `doLowerCase: true,
 *   stripAccents: null, tokenizeChineseChars: true` -- the correct settings for
 *   bert-base-UNCASED, which is what v3 shipped. Those three flags are exactly the
 *   ones that differ on a CASED multilingual encoder (v17's candidate,
 *   distilbert-base-multilingual-cased, is do_lower_case=false).
 *
 *   That made this check actively dangerous rather than merely stale: pointed at a
 *   cased model it would have lowercased the probe text on the TS side, compared it
 *   against a golden file generated by a tokenizer that did NOT lowercase, and the
 *   DIFF WOULD HAVE BEEN REAL -- but the natural reading of a red parity check is
 *   "the TS tokenizer is broken", not "the harness is configured for a different
 *   model". The failure mode this repo actually fears is the opposite one and is
 *   worse: a golden file regenerated with matching-but-wrong flags turns this into a
 *   green check that proves nothing, and production then tokenizes every request
 *   differently from training. That is precisely the defect the byte-exact
 *   tokenizer was written to fix (recall 88.5 -> 92.3 at flat FPR).
 *
 *   So the options now come from the SAME tokenizer_config.json the production
 *   loader reads (lib/ml/onnxBackend.ts:377-399), and a missing config is a hard
 *   failure rather than a silent fallback to the uncased defaults.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { BertTokenizer, parseVocabTxt } from "../../lib/ml/bertTokenizer";

const ROOT = path.resolve(__dirname, "..", "..");

interface Golden {
  text: string;
  input_ids: number[];
  attention_mask: number[];
}

/**
 * Optional first entry of a golden file, written by dump-hf-tokenization.py.
 *
 * This is what closes the hole described above. Reading the flags from
 * tokenizer_config.json makes the TS side agree with the MODEL, but it cannot by
 * itself detect a golden file produced by a DIFFERENT tokenizer: both sides would
 * be self-consistently wrong and the check would pass. The golden now carries the
 * flags it was generated under, and they are asserted against the model dir, so
 * "this golden belongs to this encoder" is verified rather than assumed.
 *
 * Older golden files predate this and have no meta entry. They are accepted with
 * a warning rather than a failure: v3/v14's golden is real evidence for the model
 * that is LIVE, and invalidating it to introduce a new check would cost more than
 * it buys.
 */
interface GoldenMeta {
  __meta__: {
    source?: string;
    vocab_size?: number;
    do_lower_case?: boolean;
    strip_accents?: boolean | null;
    tokenize_chinese_chars?: boolean;
  };
}

/** Mirrors the production loader's reading of tokenizer_config.json. */
interface TokenizerConfig {
  do_lower_case?: boolean;
  strip_accents?: boolean | null;
  tokenize_chinese_chars?: boolean;
  model_max_length?: number;
}

function parseArgs(argv: string[]): { modelDir: string; golden: string; maxLength: number } {
  let modelDir = path.join(ROOT, "models", "ml-classifier-v3");
  let golden = path.join(__dirname, "_hf-tokenization-golden.json");
  let maxLength = 128;
  for (let i = 0; i < argv.length; i++) {
    const next = argv[i + 1];
    if (argv[i] === "--model-dir" && next) modelDir = path.resolve(ROOT, next);
    else if (argv[i] === "--golden" && next) golden = path.resolve(ROOT, next);
    else if (argv[i] === "--max-length" && next) maxLength = Number(next);
  }
  // Convention: tokenizer files live in <model-dir>/tokenizer_config/ (v3..v16).
  // Accept a directory that IS the tokenizer dir as well, so --model-dir can point
  // straight at an exported HF folder.
  const nested = path.join(modelDir, "tokenizer_config");
  const tokDir = fs.existsSync(path.join(nested, "vocab.txt")) ? nested : modelDir;
  return { modelDir: tokDir, golden, maxLength };
}

function loadTokenizerConfig(tokDir: string): TokenizerConfig {
  const p = path.join(tokDir, "tokenizer_config.json");
  if (!fs.existsSync(p)) {
    console.error(
      `[FATAL] no tokenizer_config.json in ${tokDir}\n` +
        "        Refusing to fall back to the bert-base-uncased defaults: on a cased\n" +
        "        encoder that would compare TS tokens against a golden file produced\n" +
        "        under different flags, and a green result would mean nothing.",
    );
    process.exit(2);
  }
  return JSON.parse(fs.readFileSync(p, "utf-8")) as TokenizerConfig;
}

function main() {
  const { modelDir, golden: goldenPath, maxLength } = parseArgs(process.argv.slice(2));

  const vocabPath = path.join(modelDir, "vocab.txt");
  if (!fs.existsSync(vocabPath)) {
    console.error(`[FATAL] no vocab.txt in ${modelDir}`);
    process.exit(2);
  }
  if (!fs.existsSync(goldenPath)) {
    console.error(
      `[FATAL] golden file missing: ${goldenPath}\n` +
        "        Generate it with scripts/ml/dump-hf-tokenization.py against the SAME\n" +
        "        encoder as --model-dir, or the comparison is meaningless.",
    );
    process.exit(2);
  }

  const cfg = loadTokenizerConfig(modelDir);
  // Same precedence the production loader uses: an absent flag takes the HF default
  // for a BertTokenizer, which is lowercase=true / chinese-chars=true, and
  // strip_accents=null meaning "follow do_lower_case".
  const doLowerCase = cfg.do_lower_case ?? true;
  const stripAccents = cfg.strip_accents ?? null;
  const tokenizeChineseChars = cfg.tokenize_chinese_chars ?? true;

  const vocab = parseVocabTxt(fs.readFileSync(vocabPath, "utf-8"));
  const tok = new BertTokenizer(vocab, {
    doLowerCase,
    stripAccents,
    tokenizeChineseChars,
    maxLength,
  });

  console.log(`model dir   : ${path.relative(ROOT, modelDir)}`);
  console.log(`golden      : ${path.relative(ROOT, goldenPath)}`);
  console.log(`vocab size  : ${vocab.size ?? Object.keys(vocab).length}`);
  console.log(
    `tokenizer   : do_lower_case=${doLowerCase} strip_accents=${String(stripAccents)} ` +
      `tokenize_chinese_chars=${tokenizeChineseChars} max_length=${maxLength}`,
  );

  const raw: (Golden | GoldenMeta)[] = JSON.parse(fs.readFileSync(goldenPath, "utf-8"));
  const meta = (raw.find((e) => "__meta__" in e) as GoldenMeta | undefined)?.__meta__;
  const golden: Golden[] = raw.filter((e): e is Golden => !("__meta__" in e));

  if (!meta) {
    console.log(
      "warning     : this golden file carries no __meta__ block, so it cannot be\n" +
        "              proven to come from this encoder. Regenerate it with\n" +
        "              scripts/ml/dump-hf-tokenization.py to add one.",
    );
  } else {
    const want = {
      do_lower_case: doLowerCase,
      strip_accents: stripAccents,
      tokenize_chinese_chars: tokenizeChineseChars,
      vocab_size: vocab.size ?? Object.keys(vocab).length,
    };
    const disagree = (Object.keys(want) as (keyof typeof want)[]).filter(
      (k) => meta[k] !== undefined && meta[k] !== want[k],
    );
    if (disagree.length) {
      console.error(
        `\n[FATAL] the golden file was generated by a DIFFERENT tokenizer than ${path.relative(
          ROOT,
          modelDir,
        )}.\n` +
          disagree
            .map((k) => `        ${k}: golden=${String(meta[k])} model=${String(want[k])}`)
            .join("\n") +
          `\n        golden source: ${meta.source ?? "unknown"}\n` +
          "        Comparing them would measure the wrong thing in whichever direction it\n" +
          "        landed. Regenerate the golden against THIS encoder:\n" +
          "          python scripts/ml/dump-hf-tokenization.py \\\n" +
          `            --tokenizer-dir ${path.relative(ROOT, modelDir)} --out <a NEW golden path>\n` +
          "        Do not overwrite another model's golden file to make this pass.",
      );
      process.exit(1);
    }
    console.log(`golden meta : from ${meta.source ?? "?"} — flags match this encoder`);
  }

  let pass = 0;
  const fails: string[] = [];

  for (const g of golden) {
    const r = tok.tokenize(g.text);
    const idsMatch =
      r.inputIds.length === g.input_ids.length && r.inputIds.every((v, i) => v === g.input_ids[i]);
    const maskMatch =
      r.attentionMask.length === g.attention_mask.length &&
      r.attentionMask.every((v, i) => v === g.attention_mask[i]);
    if (idsMatch && maskMatch) {
      pass++;
    } else {
      // find first divergence for a readable diff
      let at = -1;
      for (let i = 0; i < Math.max(r.inputIds.length, g.input_ids.length); i++) {
        if (r.inputIds[i] !== g.input_ids[i]) {
          at = i;
          break;
        }
      }
      fails.push(
        `\n  CASE: ${JSON.stringify(g.text)}\n` +
          `    first diff at index ${at}: TS=${r.inputIds[at]} HF=${g.input_ids[at]}\n` +
          `    TS ids: [${r.inputIds.slice(0, Math.max(at + 3, 12)).join(",")}...]\n` +
          `    HF ids: [${g.input_ids.slice(0, Math.max(at + 3, 12)).join(",")}...]`,
      );
    }
  }

  console.log(`\nTokenizer parity: ${pass}/${golden.length} cases match HF exactly.`);
  if (fails.length) {
    console.log(`\nFAILURES (${fails.length}):${fails.join("")}`);
    console.log(
      "\nBefore assuming the TS tokenizer is wrong: confirm the golden file was\n" +
        "generated against this same encoder. A cased/uncased mismatch produces\n" +
        "exactly this diff shape.",
    );
    process.exit(1);
  }
  console.log("PARITY OK — production tokens now match training tokens.");
}

main();
