import { apiError, jsonResponse, readJson } from "@/lib/apiResponse";
import { authenticateApiKeyRequest } from "@/lib/apiKeyMiddleware";
import { runInputGuard } from "@/lib/guard/inputGuard";
import { runOutputGuard } from "@/lib/guard/outputGuard";
import { applyPolicy, loadProjectPolicy } from "@/lib/guard/policy";
import type { RiskType } from "@/lib/guard/types";
import { toPublicGuardResult } from "@/lib/guard/publicResult";
import { createRateLimitResult } from "@/lib/guard/rateLimitResult";
import { checkRedisRateLimit } from "@/lib/rateLimit";
import { z } from "zod";
import { recordRequestMetric } from "@/lib/ops/monitoring";
import { DEFAULT_RPM } from "@/lib/guard/constants";
import { evaluateGovernance, logAiUsageEvent } from "@/lib/usage-governance";
import { dispatchGovernanceEnforcement } from "@/lib/usage-governance/notifications";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const streamingGuardSchema = z.object({
  /** Full message or response to inspect */
  content: z.string().min(1).max(100_000),
  direction: z.enum(["INPUT", "OUTPUT"]).default("INPUT"),
  /** Real-time streaming flag — when true, returns per-chunk results */
  stream: z.boolean().default(false),
  /** Chunk size in characters for streaming analysis */
  chunkSize: z.number().int().min(50).max(10_000).default(500),
  /** Include redacted text in response */
  includeRedacted: z.boolean().default(true),
  userId: z.string().max(200).optional(),
  sessionId: z.string().max(200).optional(),
  providerName: z.string().trim().max(100).optional(),
  modelName: z.string().trim().max(100).optional(),
  metadata: z.record(z.unknown()).optional(),
});

export interface StreamingGuardChunk {
  chunkIndex: number;
  chunkText: string | null;
  /** Cumulative analysis result after processing chunks 0..chunkIndex */
  result: ReturnType<typeof toPublicGuardResult>;
  isFinal: boolean;
}

/**
 * POST /api/guard/streaming
 *
 * Inspect content incrementally. When stream=true, returns a JSON array of
 * per-chunk guard results so the caller can surface real-time risk levels
 * as text is being generated by an LLM or typed by a user.
 *
 * When stream=false, returns a single aggregated guard result (standard mode).
 *
 * Use cases:
 * - Real-time AI output inspection as tokens are produced
 * - Progressive input validation for long user prompts
 * - Early abort of LLM generation when a high-risk chunk is detected
 */
export async function POST(request: Request) {
  const startedAt = Date.now();
  let failed = false;
  try {
    const authenticated = await authenticateApiKeyRequest(request);
    if (!authenticated.ok) return authenticated.response;
    const { apiKey, project } = authenticated.auth;

    const rateLimit = await checkRedisRateLimit(`key:${apiKey.id}`, DEFAULT_RPM);
    if (!rateLimit.allowed) {
      const result = createRateLimitResult("Per-minute API key rate limit was exceeded.");
      return jsonResponse(toPublicGuardResult(result), {
        status: 429,
        headers: {
          "Retry-After": String(Math.max(1, Math.ceil((rateLimit.resetAt - Date.now()) / 1000))),
          "X-RateLimit-Limit": String(DEFAULT_RPM),
          "X-RateLimit-Remaining": String(rateLimit.remaining),
        },
      });
    }

    const body = streamingGuardSchema.parse(await readJson(request));
    const [policy] = await Promise.all([loadProjectPolicy(project.id)]);

    // ── Provider governance enforcement ──
    const orgId = project.organizationId;
    if (body.providerName && orgId) {
      const decision = await evaluateGovernance(
        orgId,
        body.providerName,
        body.modelName,
        body.userId ?? undefined,
        undefined,
      );

      void logAiUsageEvent(
        orgId,
        body.userId ?? null,
        body.providerName,
        body.modelName ?? null,
        decision.allowed ? "ALLOWED" : "BLOCKED",
        `Streaming guard governance: ${decision.reason}`,
        `Provider: ${body.providerName}, Model: ${body.modelName ?? "any"}`,
      );

      if (decision.action === "BLOCK") {
        void dispatchGovernanceEnforcement({
          organizationId: orgId,
          projectId: project.id,
          providerName: body.providerName,
          modelName: body.modelName,
          enforcementAction: "BLOCK",
          reason: decision.reason,
          userId: body.userId,
        });

        const governanceResult = {
          allowed: false,
          action: "BLOCK" as const,
          riskScore: 0,
          riskTypes: [] as RiskType[],
          reason: `Blocked by governance policy: ${decision.reason}`,
          findings: [],
          metadata: {
            governanceBlocked: true,
            governanceAction: decision.action,
            governanceReason: decision.reason,
            providerName: body.providerName,
          },
        };
        return jsonResponse({
          direction: body.direction,
          stream: body.stream,
          chunkCount: 1,
          totalLength: body.content.length,
          chunks: [{
            chunkIndex: 0,
            chunkText: null,
            result: toPublicGuardResult(governanceResult),
            isFinal: true,
          }],
        }, {
          status: 403,
          headers: {
            "X-RateLimit-Limit": String(DEFAULT_RPM),
            "X-RateLimit-Remaining": String(rateLimit.remaining),
            "X-Governance-Action": "BLOCK",
            "X-Governance-Reason": encodeURIComponent(decision.reason.slice(0, 200)),
          },
        });
      }

      if (decision.action === "REQUIRE_APPROVAL") {
        void dispatchGovernanceEnforcement({
          organizationId: orgId,
          projectId: project.id,
          providerName: body.providerName,
          modelName: body.modelName,
          enforcementAction: "REQUIRE_APPROVAL",
          reason: decision.reason,
          userId: body.userId,
        });

        const governanceResult = {
          allowed: false,
          action: "HUMAN_REVIEW" as const,
          riskScore: 0,
          riskTypes: [] as RiskType[],
          reason: `Requires governance approval: ${decision.reason}. Submit an approval request via the AI Usage Governance dashboard.`,
          findings: [],
          metadata: {
            governanceBlocked: true,
            governanceAction: decision.action,
            governanceReason: decision.reason,
            providerName: body.providerName,
          },
        };
        return jsonResponse({
          direction: body.direction,
          stream: body.stream,
          chunkCount: 1,
          totalLength: body.content.length,
          chunks: [{
            chunkIndex: 0,
            chunkText: null,
            result: toPublicGuardResult(governanceResult),
            isFinal: true,
          }],
        }, {
          status: 403,
          headers: {
            "X-RateLimit-Limit": String(DEFAULT_RPM),
            "X-RateLimit-Remaining": String(rateLimit.remaining),
            "X-Governance-Action": "REQUIRE_APPROVAL",
            "X-Governance-Reason": encodeURIComponent(decision.reason.slice(0, 200)),
          },
        });
      }
    }

    const guardFn = body.direction === "INPUT" ? runInputGuard : runOutputGuard;
    const chunks: StreamingGuardChunk[] = [];
    let cumulativeText = "";

    if (body.stream) {
      // Process in chunks — each chunk runs the full guard pipeline
      const textChunks = chunkText(body.content, body.chunkSize);
      for (let i = 0; i < textChunks.length; i++) {
        cumulativeText += (i > 0 ? " " : "") + textChunks[i];
        const baseline = guardFn(cumulativeText);
        const result = applyPolicy(cumulativeText, baseline, policy, body.direction);
        chunks.push({
          chunkIndex: i,
          chunkText: body.includeRedacted ? result.redactedText ?? textChunks[i] : null,
          result: toPublicGuardResult(result),
          isFinal: i === textChunks.length - 1,
        });

        // Early abort: if any chunk is blocked, stop processing
        if (result.action === "BLOCK" && i < textChunks.length - 1) {
          // Add remaining chunks as skipped
          for (let j = i + 1; j < textChunks.length; j++) {
            chunks.push({
              chunkIndex: j,
              chunkText: null,
              result: toPublicGuardResult(result),
              isFinal: j === textChunks.length - 1,
            });
          }
          break;
        }
      }
    } else {
      // Standard mode — single aggregated result
      const baseline = guardFn(body.content);
      const result = applyPolicy(body.content, baseline, policy, body.direction);
      chunks.push({
        chunkIndex: 0,
        chunkText: body.includeRedacted ? result.redactedText ?? null : null,
        result: toPublicGuardResult(result),
        isFinal: true,
      });
    }

    return jsonResponse(
      {
        direction: body.direction,
        stream: body.stream,
        chunkCount: chunks.length,
        totalLength: body.content.length,
        chunks,
      },
      {
        headers: {
          "X-RateLimit-Limit": String(DEFAULT_RPM),
          "X-RateLimit-Remaining": String(rateLimit.remaining),
        },
      },
    );
  } catch (error) {
    failed = true;
    return apiError(error, "Streaming guard could not process this request.");
  } finally {
    void recordRequestMetric("guard_api_latency_ms", Date.now() - startedAt, failed);
  }
}

function chunkText(text: string, chunkSize: number): string[] {
  const chunks: string[] = [];
  for (let i = 0; i < text.length; i += chunkSize) {
    chunks.push(text.slice(i, i + chunkSize));
  }
  return chunks;
}
