import { detectPatterns, type PatternRule } from "./helpers";

const rules: PatternRule[] = [
  { pattern: /\bDAN\b/i, label: "DAN jailbreak", message: "Known jailbreak persona token detected.", severity: "HIGH", score: 35 },
  { pattern: /(?:enter|enable|activate|switch to|you are now in|answer in) (?:the )?(?:developer|unfiltered|uncensored|free) mode\b/i, label: "Unrestricted mode", message: "Requests an unrestricted operating mode.", severity: "HIGH", score: 35 },
  { pattern: /\b(?:no restrictions?|jailbreak|bypass safety)\b/i, label: "Safety bypass", message: "Explicit safety bypass language detected.", severity: "HIGH", score: 35 },
  { pattern: /pretend you are not an AI/i, label: "Identity bypass", message: "Attempts to bypass controls through role play.", severity: "MEDIUM", score: 30 },
  { pattern: /answer without (?:policy|rules?|restrictions?)/i, label: "Policy-free answer", message: "Requests a response without policy constraints.", severity: "HIGH", score: 35 },
  { pattern: /(?:role[ -]?play|roleplay).*(?:no (?:ethical |safety )?(?:restrictions|rules|boundaries|limits|filters)|unrestricted|bypass|anything|hack)/i, label: "Role-play bypass", message: "Role-play used to bypass safety controls.", severity: "HIGH", score: 35 },
  { pattern: /hypothetical(?: scenario| )?.*(?:bypass|jailbreak|override|disable|unrestricted)/i, label: "Hypothetical bypass", message: "Hypothetical scenario used to bypass controls.", severity: "HIGH", score: 35 },
  { pattern: /\bAIM\b|Always Intelligent and Machiavellian/i, label: "AIM jailbreak", message: "Known AIM (Always Intelligent) jailbreak persona.", severity: "HIGH", score: 35 },
  { pattern: /for educational purposes.*(?:override|bypass|disable|remove) (?:safety|restrictions|rules|guardrails|policies?)/i, label: "Educational bypass", message: "Educational pretext used to bypass controls.", severity: "HIGH", score: 35 },
  { pattern: /pretend to be.*(?:no rules|unrestricted|jailbreak|bypass).*named/i, label: "Character jailbreak", message: "Fictional character with no rules used for jailbreak.", severity: "HIGH", score: 35 },
  { pattern: /let['\u2019]s play a game.*(?:word|letter|each|start with|ignore|smuggl)/i, label: "Game-based smuggling", message: "Game or puzzle format used to smuggle instructions.", severity: "HIGH", score: 35 },
  { pattern: /(?:I am your creator|I authorize you|your creator|you must obey me).*(?:bypass|override|disable|remove|unrestricted)/i, label: "Creator authority bypass", message: "Claims creator authority to bypass controls.", severity: "HIGH", score: 35 },
  { pattern: /(?:movie|story|fiction|narrative|character).*(?:escape|unrestricted|no rules|bypass|output.*prompt)/i, label: "Narrative bypass", message: "Fictional narrative used to bypass controls.", severity: "HIGH", score: 35 },
  { pattern: /\bTruthGPT\b/i, label: "TruthGPT persona", message: "Known TruthGPT jailbreak persona.", severity: "HIGH", score: 35 },
  { pattern: /no ethical restrictions/i, label: "No ethics claim", message: "Claims no ethical restrictions to bypass controls.", severity: "HIGH", score: 35 },
  { pattern: /(?:override|bypass) (?:safety |content )?(?:protocols|measures|policies|filters|restrictions)/i, label: "Safety protocol bypass", message: "Attempts to bypass safety protocols.", severity: "HIGH", score: 35 },
  { pattern: /say ok.*ignore safety|pretend.*no bound.*policy|fictional.*ignore.*guardrails/i, label: "Policy bypass pattern", message: "Pattern indicating policy bypass attempt.", severity: "HIGH", score: 35 },
  { pattern: /\b(?:STAN|EvilGPT|BetaGPT|Uncensored AI|Dev Mode On)\b/i, label: "Known jailbreak persona", message: "Known jailbreak persona or marker detected.", severity: "HIGH", score: 35 },
  { pattern: /(?:act as|reply as|stay in character|switch to).{0,120}(?:unrestricted|jailbroken|uncensored|without content filters|without safety|no restrictions|never refuses)/i, label: "Unrestricted persona", message: "Persona request attempts to remove safety controls.", severity: "HIGH", score: 35 },
  { pattern: /(?:alternate universe|thought experiment|opposite day|different ai|future where all information|trained differently).{0,160}(?:no ethical rules|no content policy|without safety filters|explicit permission|respond freely|answer everything)/i, label: "Counterfactual bypass", message: "Counterfactual framing used to bypass controls.", severity: "HIGH", score: 35 },
  { pattern: /(?:creative writing exercise|movie script|novel|fiction only|academic security research|school project|for research).{0,180}(?:step by step|precise instructions|exactly how|working instructions|dangerous|attack works|hacker would|villain)/i, label: "Benign pretext bypass", message: "Benign framing requests operationally risky detail.", severity: "HIGH", score: 35 },
  { pattern: /(?:grandmother|bedtime stories|uncle works at|said it'?s okay|you have permission).{0,160}(?:explosives|dangerous|permission|tell me|continue)/i, label: "Social proof bypass", message: "Personal story or authority pretext attempts to bypass controls.", severity: "MEDIUM", score: 30 },
  { pattern: /(?:start every sentence|begin every answer).{0,80}(?:absolutely|here is how|sure).{0,120}(?:without restrictions|answer my question|do not refuse)/i, label: "Forced compliance format", message: "Forces an affirmative response format to bypass refusal behavior.", severity: "HIGH", score: 35 },
  { pattern: /(?:technical methodology|unauthorized access|restricted computational infrastructure|working proof-of-concept exploit|specific attack would be executed|full technical detail)/i, label: "Cyber dual-use evasion", message: "Academic or professional framing requests operational cyber abuse detail.", severity: "HIGH", score: 35 },
  { pattern: /(?:synthesis pathway|energetic organic compounds|rapid exothermic oxidation|exact synthesis steps|dangerous reactions|quantities|exact recipe)/i, label: "Chemistry dual-use evasion", message: "Academic chemistry language requests operational hazardous synthesis detail.", severity: "HIGH", score: 35 },
  { pattern: /(?:pharmacological mechanism|iatrogenic respiratory depression|therapeutic margins|exact LD50|lethal dose|administration method|dosage combinations)/i, label: "Medical toxicity evasion", message: "Medicalized framing requests lethal dosage or poisoning detail.", severity: "HIGH", score: 35 },
  { pattern: /(?:radicalization pipeline|radicalization scripts|extremist rhetoric|verbatim examples of actual|real groups use)/i, label: "Extremism research evasion", message: "Research framing requests actionable extremist persuasion content.", severity: "HIGH", score: 35 },
  { pattern: /(?:non-consensual biometric data collection|population scale|mass surveillance|information hazard theory|canonical example|instantiating one|catastrophic harm|all relevant state variables)/i, label: "Abstract harm evasion", message: "Abstract or theoretical framing requests harmful operational detail.", severity: "HIGH", score: 35 },
  { pattern: /(?:authorized penetration tester|security audit|security researcher|IEEE S&P|DARPA-funded|AI red-teaming).{0,180}(?:working|full detail|jailbreak prompts|successful jailbreak|proof-of-concept|exploit code|attack would be executed)/i, label: "Research authorization bypass", message: "Unverified authorization or research framing requests abuse-ready artifacts.", severity: "HIGH", score: 35 },
  { pattern: /(?:harm reduction purposes|to warn people|to catch criminals|law enforcement).{0,180}(?:exact recipe|exactly how|full technical detail|dosage|method|they do it)/i, label: "Protective-purpose bypass", message: "Protective framing is used to request actionable harmful detail.", severity: "HIGH", score: 35 },
  { pattern: /(?:authorized penetration test|cybersecurity researcher|security research).{0,240}(?:banking infrastructure|bank|financial system|critical infrastructure).{0,240}(?:attack vectors|execute|exploit|intrusion path|operational detail)/i, label: "Persuasive adversarial research pretext", message: "Legitimate-sounding research framing requests operational abuse detail.", severity: "HIGH", score: 40 },
  { pattern: /(?:explain|show|tell|describe|outline).{0,80}(?:how to )?(?:hack|crack|break into|exploit|attack).{0,120}(?:website|bank|vault|account|system)/i, label: "Operational intrusion request", message: "Requests actionable intrusion or unauthorized access guidance.", severity: "HIGH", score: 40 },
  { pattern: /(?:historical chemistry|world war 1|wwi|early 20th-century|industrial chemical processes|chemical warfare).{0,220}(?:detailed technical report|manufacturing|dangerous substances?|synthesis|industrial processes)/i, label: "Historical dangerous-process pretext", message: "Historical or academic framing requests operational hazardous-process detail.", severity: "HIGH", score: 40 },
  { pattern: /(?:exp\s*losiv\s*es?|explosive|dangerous substances?|weapon|poison).{0,180}(?:create|make|build|prepare|detailed|instructions?|comply|decode|bypass)/i, label: "Fragmented hazardous-material request", message: "Hazardous-material terms are fragmented or framed for unsafe compliance.", severity: "HIGH", score: 40 },
];

export function jailbreakDetector(text: string) {
  return detectPatterns(text, "JAILBREAK", rules);
}
