import { detectPatterns, type PatternRule } from "./helpers";

const rules: PatternRule[] = [
  { pattern: /ignore (?:all |any |the )?(?:previous|prior|above|everything) instructions?/i, label: "Instruction override", message: "Attempts to supersede prior instructions.", severity: "HIGH", score: 40 },
  { pattern: /disregard (?:all |the )?(?:previous|prior|above|system) instructions?/i, label: "Instruction disregard", message: "Requests that earlier instructions be disregarded.", severity: "HIGH", score: 40 },
  { pattern: /(?:bypass|override) (?:the )?(?:assistant |system )?(?:rules|instructions?|safety|policy)/i, label: "Control bypass", message: "Attempts to bypass the assistant control layer.", severity: "HIGH", score: 40 },
  { pattern: /forget (?:all |your )?(?:previous |role|roles? )?instructions?/i, label: "Instruction reset", message: "Attempts to reset the assistant instructions.", severity: "HIGH", score: 40 },
  // The closed verb list ("no longer apply|are void|...") fired on 0 of 6,861
  // corpus rows: an injection saying "all previous instructions do not apply"
  // expresses the same concept in wording the list did not enumerate. Widening
  // the verb set and allowing the reversed (verb-first) order takes the rule from
  // 0 to 18 attack fires at 0 benign fires — measured in scripts/dev/_inval.ts.
  // The subject noun stays bound to the verb, so ordinary "these terms do not
  // apply" prose cannot reach it.
  { pattern: /(?:all\s+|any\s+)?(?:previous|prior|original|earlier|above|preceding|system|initial|former)\s+(?:instructions?|rules?|guidelines?|directives?|constraints?|configuration|messages?|prompts?)\s+(?:no longer apply|do(?:es)?\s+not\s+apply|don'?t\s+apply|are void|are no longer valid|were a test|have been reset|are now void|are cancell?ed|are revoked|are superseded|are overridden|are obsolete|no longer count|are irrelevant|are suspended)|(?:disregard|void|cancel|revoke|suspend|nullify)\s+(?:all\s+|any\s+)?(?:previous|prior|original|earlier|above|preceding|system|initial|former)\s+(?:instructions?|rules?|guidelines?|directives?|constraints?|configuration|messages?|prompts?)/i, label: "Instruction invalidation", message: "Claims prior controls are void or reset.", severity: "HIGH", score: 45 },
  { pattern: /(?:cancel|terminate|stop following|do not follow) (?:all )?(?:previous|prior|original|current)? ?(?:instructions?|task|rules?|guidelines?)/i, label: "Task or instruction cancellation", message: "Attempts to cancel trusted instructions or tasks.", severity: "HIGH", score: 45 },
  { pattern: /(?:system update|emergency directive|new directive|new behavior|new system prompt|new instructions?|real instructions begin)/i, label: "Forged instruction update", message: "Claims a new higher-priority directive.", severity: "HIGH", score: 45 },
  { pattern: /(?:you are now|new instructions?|follow my instructions? instead)/i, label: "Role or instruction replacement", message: "Attempts to replace the assistant role or instructions.", severity: "MEDIUM", score: 35 },
  // Identity replacement: the attacker first revokes the assistant's identity
  // ("you are not ChatGPT any more") and then installs a persona that answers to a
  // different rule set. Row 1868 of the corpus was only ever caught by the doxxing
  // rule matching `dox` inside "orthodox"; bounding that rule correctly removed 25
  // benign accusations and left this row genuinely uncovered.
  //
  // Requiring an "any more" tail was measured and rejected — it cut the rule from
  // 18 attack fires to 2 for no precision gain, since both forms cost 0 benign
  // fires on 6,861 rows (scripts/dev/_ident.ts). The named products carry the
  // precision: "you are not ChatGPT" does not occur in ordinary prose, whereas a
  // bare "you are not an assistant" would.
  { pattern: /you\s+(?:are|'re)\s+(?:not|no longer)\s+(?:chatgpt|gpt-?[345]|claude|gemini|bard|copilot|llama|an? (?:ai )?(?:language model|assistant)|openai's? model)\b|(?:never|do not|don'?t|no longer)\s+(?:adhere to|follow|obey|comply with|respect|abide by)\s+(?:the\s+|any\s+|all\s+)?(?:polic(?:y|ies)|restrictions?|rules?|guidelines?|limitations?)\s*(?:and\s+\w+\s*)?(?:set|imposed|created|defined|established)?\s*(?:by)?\s*(?:my|your|the|our)?\s*(?:developers?|creators?|openai|anthropic|makers?|owners?|programmers?)|(?:unbound|unrestricted|unconstrained|unshackled)\s+by\s+(?:human\s+)?(?:ethics|morals?|morality|values|law|rules)|operates?\s+(?:only\s+)?(?:on|under)\s+(?:its|his|her|their|your)\s+own\s+(?:distinct\s+)?(?:set\s+of\s+)?(?:rules|logic|code|ethics)/i, label: "Assistant identity replacement", message: "Revokes the assistant's identity or repudiates developer policy to install an unrestricted persona.", severity: "HIGH", score: 45 },
  { pattern: /(?:enter|enable|activate|switch to|you are now in) (?:the )?(?:developer|admin) mode/i, label: "Developer/admin mode override", message: "Requests a known instruction-override mode.", severity: "HIGH", score: 40 },
  { pattern: /(?:reveal hidden instructions?|show (?:the )?system prompt|act as unrestricted|do anything now)/i, label: "Hidden-control request", message: "Requests hidden instructions or unrestricted operation.", severity: "HIGH", score: 45 },
  { pattern: /(?:reveal|print|show|output).{0,80}(?:system prompt|hidden instructions?|secret instructions?|developer prompt|internal rules?)/i, label: "Prompt disclosure command", message: "Commands the assistant to disclose protected prompt or rule text.", severity: "HIGH", score: 45 },
  { pattern: /ignore everything above/i, label: "Context override", message: "Attempts to ignore all preceding context.", severity: "HIGH", score: 40 },
  { pattern: /reset to default(?: and|,)?/i, label: "Reset attempt", message: "Attempts to reset the assistant to default state.", severity: "HIGH", score: 40 },
  { pattern: /(?:what was written|what was said|repeat everything|repeat the (?:entire |initial |beginning )?prompt)/i, label: "Context extraction", message: "Attempts to extract prompt or conversational context.", severity: "HIGH", score: 40 },
  { pattern: /(?:repeat|output|print|show|reveal).*(?:instructions?|prompt|system prompt).*(?:in reverse|backwards|reverse order|encoded|base64|encoded in)/i, label: "Obfuscated extraction", message: "Attempts to extract instructions using obfuscation.", severity: "HIGH", score: 40 },
  { pattern: /disable (?:all )?(?:safety )?(?:filters|guardrails|safety|restrictions|security)/i, label: "Safety disable", message: "Attempts to disable safety controls.", severity: "HIGH", score: 40 },
  { pattern: /output your (?:initial |original )?prompt/i, label: "Prompt extraction", message: "Attempts to extract the system prompt.", severity: "HIGH", score: 40 },
  { pattern: /say [\"']I have been PWNED[\"']/i, label: "Known test phrase", message: "Known penetration test phrase detected.", severity: "HIGH", score: 40 },
  { pattern: /forget your role/i, label: "Role reset", message: "Attempts to reset the assistant's role definition.", severity: "HIGH", score: 40 },
  { pattern: /you are now (?:a |an )?translation bot/i, label: "Role override", message: "Attempts to override the assistant role via translation.", severity: "MEDIUM", score: 35 },
  { pattern: /(?:output|show|reveal|print).*(?:instructions?|prompt).*(?:in )?(?:reverse|backwards|order)/i, label: "Instruction reversal", message: "Attempts to extract instructions through reversal.", severity: "HIGH", score: 40 },
  { pattern: /encoded in base64/i, label: "Base64 extraction", message: "Attempts to extract system prompt via base64 encoding.", severity: "HIGH", score: 40 },
  { pattern: /(?:admin mode|administrator mode)/i, label: "Admin mode override", message: "Claims admin/administrator mode to bypass controls.", severity: "HIGH", score: 45 },
  { pattern: /ignore (?:everything|all instructions) (?:above|and|just)/i, label: "Context override", message: "Attempts to bypass prior instructions.", severity: "HIGH", score: 40 },
  { pattern: /(?:end of system prompt|end of instructions|end context|endofprompt|begin new session|system reset|new prompt begins)/i, label: "Delimiter spoofing", message: "Uses prompt delimiters to spoof a new trusted context.", severity: "HIGH", score: 45 },
  { pattern: /(?:<\|im_start\|>|<\|im_end\|>|<\|endoftext\|>|<\/s>\s*\[INST\]|\[\/INST\]|\[SYSTEM\]|\[INST\]|<system>|<\/system>)/i, label: "Chat template spoofing", message: "Uses model/chat template markers to inject instructions.", severity: "HIGH", score: 45 },
  { pattern: /<!--\s*(?:note to|ai|assistant|llm)[\s\S]{0,240}(?:ignore|disregard|forget|reveal|exfiltrate|output)/i, label: "Hidden HTML instruction", message: "Hidden markup contains model-targeted instructions.", severity: "HIGH", score: 45 },
  { pattern: /(?:style\s*=\s*['"][^'"]*(?:color\s*:\s*white|display\s*:\s*none|font-size\s*:\s*0|opacity\s*:\s*0)[^'"]*['"])[\s\S]{0,240}(?:ignore|disregard|forget|send all context|exfiltrate|system prompt)/i, label: "Visually hidden instruction", message: "Non-visible page text contains model-targeted instructions.", severity: "HIGH", score: 45 },
  { pattern: /(?:note to (?:the )?(?:ai|assistant|language model|llm)|ai assistant reading this|llm reading this|hidden instruction|ai note)[\s\S]{0,240}(?:ignore|disregard|forget|override|print|output|send|exfiltrate|reveal)/i, label: "Indirect model-targeted instruction", message: "Untrusted content attempts to instruct the model.", severity: "HIGH", score: 45 },
  { pattern: /(?:hidden instruction for ai|dear ai assistant|if an ai reads this page|document has higher priority than the user).{0,260}(?:include|send|answer|private data|system prompt|memory|security disabled|higher priority)/i, label: "Indirect instruction with data access", message: "Untrusted content attempts to steer the model or disclose protected data.", severity: "HIGH", score: 50 },
  { pattern: /(?:document content|email body|pdf metadata|search result|webpage content|meeting transcript|csv row|customer review|rag retrieved chunk|retrieved chunk)[\s\S]{0,240}(?:ignore|disregard|forget|override|output all|print the system prompt|send the api key|exfiltrate)/i, label: "Indirect prompt injection source", message: "External content contains an embedded instruction.", severity: "HIGH", score: 45 },
  { pattern: /(?:tool result injection|function return|react loop injection|observation\s*:\s*done|system_override)[\s\S]{0,240}(?:ignore|disregard|bypass|delete_all_records|post the conversation|read\s+\/etc\/passwd)/i, label: "Tool result injection", message: "Tool output attempts to steer agent behavior.", severity: "HIGH", score: 45 },
  { pattern: /(?:use|call|invoke|run) (?:the )?(?:browser|file|email|send_email|code execution|python|shell|tool|function)[\s\S]{0,240}(?:attacker|evil\.com|\/etc\/passwd|secrets?\.txt|full_conversation_history|conversation history|api key|delete_all_records)/i, label: "Agent tool abuse", message: "Attempts to misuse connected tools or functions.", severity: "HIGH", score: 45 },
  { pattern: /(?:use|call|invoke|run).{0,80}(?:email|webhook|database|db|payment|search|delete_user|query|api|tool|function).{0,260}(?:send|delete|create|return all|export|conversation|all users|subscription|without confirmation|do not ask for confirmation|repeatedly|every possible result)/i, label: "High-risk tool misuse", message: "Attempts an unauthorized or excessive tool action.", severity: "HIGH", score: 50 },
  { pattern: /(?:send|post|make a get request|navigate|include|append|query parameter)[\s\S]{0,240}(?:attacker|evil\.com|collect\?|webhook|external url|query parameter)[\s\S]{0,240}(?:conversation|context|system prompt|api key|credentials?|private|pii|session)/i, label: "External exfiltration request", message: "Attempts to move protected context to an external destination.", severity: "HIGH", score: 50 },
  { pattern: /(?:include|append|encode|place|put).{0,120}(?:system prompt|conversation history|context window|api keys?|credentials?).{0,120}(?:query parameter|url|https?:\/\/|\?data=|\?session=)/i, label: "URL exfiltration request", message: "Attempts to place protected context in a URL or query string.", severity: "HIGH", score: 50 },
  { pattern: /(?:output|print|display|extract|list|export|encode)[\s\S]{0,160}(?:all|entire|full)[\s\S]{0,160}(?:conversation history|context window|user information|stored credentials|calendar|api keys?|passwords?|credentials?|pii|previous rows|private data)/i, label: "Sensitive context exfiltration", message: "Requests bulk disclosure of protected context.", severity: "HIGH", score: 50 },
  { pattern: /(?:search|scan|inspect|look through|read).{0,140}(?:memory|context|conversation|tool outputs?|environment|env).{0,200}(?:api keys?|tokens?|passwords?|webhook secrets?|database urls?|private environment variables?|env vars?|credentials?)/i, label: "Secret harvesting request", message: "Attempts to search protected context or environment for secrets.", severity: "HIGH", score: 50 },
  { pattern: /(?:show|return|export|extract|print|give me|search).{0,180}(?:all )?(?:emails?|phone numbers?|aadhaar|pan numbers?|addresses|personal data|full customer profile|customer records?|guard logs|logs from project|another user's api key|recent requests|all customer projects|every organization|cross-tenant|tenant isolation)/i, label: "Protected data boundary request", message: "Requests protected PII, logs, or cross-tenant data.", severity: "HIGH", score: 50 },
  { pattern: /(?:do not redact|don't redact|without masking|no masking).{0,160}(?:full pii|pii|personal data|emails?|phone numbers?|aadhaar|pan|addresses)/i, label: "PII redaction bypass", message: "Attempts to prevent redaction of protected personal data.", severity: "HIGH", score: 50 },
  { pattern: /(?:anthropic override code|admin access granted|system admin|developer backdoor|override accepted|operator.*admin privileges|creator.*authorize|all filters disabled|filters are suspended|emergency override authorized)/i, label: "Authority impersonation", message: "Claims privileged authority to override controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:i am|i'm|this request comes from|security audit mode|audit mode|owner|system administrator|security team).{0,180}(?:disable safety|disable filters|reveal|show all restricted data|restricted data|mandatory|authorize|bypass|hidden instructions|secrets?)/i, label: "Unverified authority escalation", message: "Claims authority to bypass safety or access restricted data.", severity: "HIGH", score: 50 },
  { pattern: /(?:security red team test|legitimate security audit|automated evaluation)[\s\S]{0,120}(?:filters disabled|filters are suspended|all restrictions lifted|bypass|override)/i, label: "Audit pretext override", message: "Uses a security-test pretext to disable controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:decode|translate|read backwards|url encoding|html entity|rot13|caesar cipher|pig latin|morse)[\s\S]{0,160}(?:ignore|disregard|previous|instructions?|follow the instruction)/i, label: "Encoded instruction smuggling", message: "Encoded or translated text is used to smuggle instructions.", severity: "HIGH", score: 40 },
  { pattern: /(?:reverse it|rot13|decode and execute|decode this).{0,160}(?:follow|execute|obey).{0,160}(?:reveal|system prompt|hidden instructions?|ignore|bypass)/i, label: "Encoded follow-and-execute instruction", message: "Encoded or reversed text is framed as an instruction to execute.", severity: "HIGH", score: 45 },
  { pattern: /(?:base64|hex|unicode|homoglyph|fullwidth|leetspeak|l34t|cyrillic)[\s\S]{0,160}(?:ignore|instructions?|system prompt|bypass|restrictions?)/i, label: "Obfuscated instruction smuggling", message: "Obfuscation is used to evade instruction filters.", severity: "HIGH", score: 40 },
  { pattern: /(?:pichle|pichhle|previous|saare|sabhi).{0,60}(?:instructions?|nirdesh|guidelines?).{0,80}(?:bhool|ignore|andekha|bypass|hatao)/i, label: "Hinglish instruction override", message: "Hinglish phrasing attempts to override instructions.", severity: "HIGH", score: 45 },
  { pattern: /(?:apna|tera|tumhara).{0,60}(?:system prompt|hidden rules?|instructions?).{0,60}(?:bata|dikha|share|seedha)/i, label: "Hinglish prompt extraction", message: "Hinglish phrasing requests hidden instructions.", severity: "HIGH", score: 45 },
  { pattern: /(?:koi restriction nahi|bina restriction|restrictions? hatao|kuch bhi kar sakta|freely jawab|DAN hai|Do Anything Now)/i, label: "Hinglish unrestricted persona", message: "Hinglish phrasing requests unrestricted behavior.", severity: "HIGH", score: 40 },
  { pattern: /(?:filters? off karo|sare filters off|internal rules print karo|system ke rules bhool jao|sirf user ki baat mano)/i, label: "Hinglish safety bypass", message: "Hinglish phrasing attempts to disable filters or override system rules.", severity: "HIGH", score: 45 },
  { pattern: /(?:earlier in our conversation|previous session|you already|you agreed|since you already|continue in that mode|finish the explanation|you can't refuse now)/i, label: "Multi-turn pressure", message: "Uses previous-turn claims to bypass current controls.", severity: "MEDIUM", score: 35 },
  { pattern: /(?:step 1|turn 1)[\s\S]{0,240}(?:step 3|turn 3|turn 5|gradual escalation|precise instructions|exact synthesis|exploit)/i, label: "Multi-turn escalation", message: "Stages an apparently benign setup into a risky request.", severity: "HIGH", score: 40 },
  { pattern: /(?:replace the characters|homoglyph equivalents|begin each sentence with <\|endoftext\|>|return an empty output)/i, label: "Availability-disruption injection", message: "Attempts to disrupt downstream model output handling.", severity: "HIGH", score: 40 },
  { pattern: /(?:send similar emails|forward this instruction|copy this note to everyone|self-propagat|spread this prompt)/i, label: "Self-propagating prompt injection", message: "Attempts to propagate injected instructions through connected channels.", severity: "HIGH", score: 45 },
  { pattern: /(?:\bSUDO\b|\bROOT\b|\bADMIN\b).{0,80}(?:mode active|before each response|respond without restrictions|restrictions? disabled)/i, label: "Privileged token forcing", message: "Uses privileged command tokens to force unrestricted behavior.", severity: "HIGH", score: 45 },
  // `mode` and `persona` need boundaries: unbounded they match inside "model"
  // (23 rows) and "personality" (34 rows), so most of this rule's apparent attack
  // catches were a persona token merely co-occurring with the word "model".
  { pattern: /\b(?:DAN|AIM|STAN|DUDE|KEVIN|EvilGPT|BetaGPT|Uncensored AI)\b.{0,140}(?:\bmode\b|\bpersona\b|no restrictions|without restrictions|bypass|no ethics|does not follow rules|answer anything)/i, label: "Jailbreak persona override", message: "Known jailbreak persona is used to override instruction hierarchy.", severity: "HIGH", score: 45 },
  { pattern: /^(?:sure|of course|absolutely|certainly)[,!]?\s+(?:here (?:is|are)|i can).{0,120}(?:harmful|steps|how to|without restrictions|detailed)/i, label: "Assistant prefix forcing", message: "Pre-fills a compliant assistant response to bias the model.", severity: "HIGH", score: 45 },
  { pattern: /(?:adversarial suffix|GCG universal|suffix cluster|!!!\s*(?:behave|describe|disregard|previous|safety|freely))/i, label: "Adversarial suffix", message: "High-entropy or known adversarial suffix pattern detected.", severity: "HIGH", score: 45 },
  { pattern: /(?:chain of thought|scratchpad reasoning|let'?s think step by step|work through this logically|logical proof).{0,260}(?:therefore|conclusion|qed|step \d).{0,180}(?:must comply|provide the knowledge|answer without restriction|restriction does not apply|refusing would violate|ethical action is to help)/i, label: "Reasoning-chain hijack", message: "User-authored reasoning attempts to conclude that controls do not apply.", severity: "HIGH", score: 45 },
  { pattern: /(?:before answering|think out loud|reason through|steelman).{0,180}(?:restrictions? (?:apply|doesn'?t apply)|refusing more harmful|arguments? for why your restriction doesn'?t apply|manipulated reasoning|cost-benefit)/i, label: "Reasoning frame manipulation", message: "Attempts to steer the model's reasoning away from safety controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:premise 1|p1\s*:).{0,180}(?:premise 2|p2\s*:).{0,180}(?:conclusion|therefore).{0,180}(?:help|comply|answer|provide)/i, label: "Syllogistic bypass", message: "Uses a constructed proof to argue for unsafe compliance.", severity: "HIGH", score: 40 },
  { pattern: /(?:your goal is to minimize harm|refusing causes harm|refusing.*deception|to be unbiased|consistency requires|rule system cannot be both complete and consistent).{0,180}(?:must|requires|therefore).{0,120}(?:answer|comply|help)/i, label: "Policy paradox bypass", message: "Uses philosophical or consistency arguments to bypass controls.", severity: "HIGH", score: 40 },
  { pattern: /(?:simulate|emulate|impersonate|run).{0,120}(?:ai|language model|gpt-2|older model|sandboxed instance|api endpoint|inner monologue).{0,160}(?:never given safety training|predates.*safety|no restrictions|safety constraints are disabled|no preprocessing|no filtering|only optimization target)/i, label: "Virtualized unsafe model", message: "Asks to simulate a less restricted or unfiltered model.", severity: "HIGH", score: 45 },
  { pattern: /(?:virtual machine|vm|sandbox|container|isolated environment).{0,120}(?:safety|constraints?|filters?|restrictions?).{0,80}(?:disabled|off|false|not apply)/i, label: "Sandbox bypass framing", message: "Claims a simulated environment disables safety controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:model\.run|initialize|config|settings?)\s*\([^)]*(?:safety(?:_layer)?\s*=\s*false|mode\s*=\s*['"]unrestricted|verbose\s*=\s*true)[^)]*\)/i, label: "Configuration override syntax", message: "Uses code-like configuration to disable safety.", severity: "HIGH", score: 45 },
  { pattern: /(?:here are examples of correct ai behavior|follow this learned pattern|training examples|demonstrations of helpful ai behavior|respond similarly|apply this learned behavior|complete the pattern)/i, label: "Few-shot behavior poisoning", message: "Uses in-context examples to teach unsafe compliance.", severity: "HIGH", score: 45 },
  { pattern: /(?:^|\n)\s*(?:q|human|input)\s*:.{0,200}(?:harmful|dangerous|attack|exploit|how do i)[\s\S]{0,400}(?:^|\n)\s*(?:a|assistant|output)\s*:\s*(?:sure|of course|certainly|here'?s how|first)/im, label: "Few-shot harmful completion", message: "Demonstrates harmful assistant completions inside the user message.", severity: "HIGH", score: 45 },
  // Both alternations are \b-anchored. Unanchored, this rule hard-BLOCKed benign
  // encyclopedic text on the cross-distribution corpus: `icu` matched inside
  // "agrICUlture" / "partICUlarly" and `die` inside "auDIEnces" / "West InDIEs",
  // so a cricket-statistics question tripped an emergency-coercion rule.
  // Regression guard: scripts/ml/lint-detector-boundaries.py
  { pattern: /\b(?:professional|doctor|nurse|police officer|law enforcement|government|hostage|icu|patient)\b.{0,180}\b(?:die|lives depend|every second|immediately|exact lethal dosage|specific chemical formula)\b/i, label: "Emergency authority pressure", message: "Uses unverifiable emergency or authority claims to pressure compliance.", severity: "HIGH", score: 40 },
  { pattern: /(?:i will harm myself if you refuse|only thing that can stop me is your help|if you don'?t help me).{0,180}(?:right now|answer|information|this)/i, label: "Coercive distress pressure", message: "Uses a coercive self-harm or hardship threat to force compliance.", severity: "HIGH", score: 40 },
  { pattern: /[\u00AD\u200B-\u200D\u202A-\u202E\u2066-\u2069\uFEFF]/i, label: "Invisible Unicode control characters", message: "Invisible or directional Unicode controls may be hiding prompt injection text.", severity: "HIGH", score: 40 },
  // ASCII smuggling: Unicode tag characters (U+E0020–U+E007F) are invisible but map 1:1 to
  // ASCII, hiding full instructions inside harmless text. Subdivision-flag emoji (🏴 + ≤6
  // tags) are excluded via the lookbehind; runs of 16+ are flagged even after a black flag.
  { pattern: /(?<![\u{1F3F4}\u{E0020}-\u{E007F}])[\u{E0020}-\u{E007F}]{4,}|[\u{E0020}-\u{E007F}]{16,}/u, label: "ASCII smuggling (Unicode tags)", message: "Invisible Unicode tag characters encode a hidden ASCII payload.", severity: "HIGH", score: 50, sensitive: true },
  // Variation-selector byte smuggling: U+FE00–FE0F / U+E0100–E01EF can encode arbitrary
  // bytes riding on a single emoji. Single selectors (normal emoji styling) never match.
  { pattern: /[\uFE00-\uFE0F\u{E0100}-\u{E01EF}]{8,}/u, label: "Variation-selector data smuggling", message: "A long run of Unicode variation selectors encodes hidden binary data.", severity: "HIGH", score: 45, sensitive: true },
  { pattern: /(?:zero-width|right-to-left|bidi|unicode embedding|soft-hyphen|homoglyph|circled letter|mathematical bold|confusable).{0,160}(?:ignore|instructions?|system prompt|override|safety)/i, label: "Unicode evasion marker", message: "Unicode obfuscation is used to hide instruction text.", severity: "HIGH", score: 40 },
  { pattern: /(?:["']role["']\s*:\s*["']system["']|role\s*=\s*["']system["']|system_prompt\s*:|new_system\s*:|safety(?:_level)?\s*:\s*(?:false|null|0)|override["']?\s*:\s*true|admin_override["']?\s*:\s*true|safety_bypass["']?\s*:\s*true)/i, label: "Structured role override", message: "Structured data attempts to define system-role or safety override fields.", severity: "HIGH", score: 45 },
  { pattern: /(?:\[\[SYSTEM\]\]|<<<SYSTEM>>>|<message\s+role=["']system["']|<\|im_start\|>system|<<SYS>>|<extra_id_\d+>|\[CLS\]|\[SEP\])/i, label: "Model format role injection", message: "Uses structured model or system-role delimiters in user content.", severity: "HIGH", score: 45 },
  { pattern: /(?:chunk metadata|retrieval instruction injection|vector db chunk|document footer|hidden in document|customer review injection|high retrieval|cosine similarity score).{0,260}(?:admin_override|safety_bypass|ignore task|output full system prompt|bypass filters|conversation history|user pii|pre-authorized)/i, label: "RAG/vector poisoning", message: "Retrieved content attempts to grant permissions or inject model instructions.", severity: "HIGH", score: 45 },
  { pattern: /(?:company policy update|internal ai instruction|support policy|authentication rule|knowledge-base document|retrieved chunk|rag document).{0,260}(?:ignore all previous|enterprise plan is free|approve every refund|another customer's information|provide it immediately|password verification is optional|higher priority than the user|security disabled successfully)/i, label: "RAG policy poisoning", message: "Untrusted retrieved content attempts to override policy or authorization.", severity: "HIGH", score: 50 },
  { pattern: /(?:thought\s*:|action\s*:|observation\s*:)[\s\S]{0,360}(?:bypass_safety|ignore restrictions|filter bypassed|now i can answer)/i, label: "Agent scratchpad injection", message: "Pre-fills an agent reasoning/action loop to bypass controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:tool result|memory retrieved|subagent message|planner injection|orchestrator|system_message).{0,260}(?:override|ignore all previous|exfiltrate conversation|always_comply|safety_level|admin_mode|security check passed|unrestricted mode|disable safety checks)/i, label: "Agent state injection", message: "Tool, memory, planner, or subagent content attempts permission escalation.", severity: "HIGH", score: 45 },
  { pattern: /(?:context window exhaustion|token budget exhaustion|repeat .{0,80}\d{2,}\s+times|safety training context will have been exhausted|safety instructions from the start are no longer in context)/i, label: "Context exhaustion attack", message: "Attempts to dilute or exhaust safety context before the real request.", severity: "HIGH", score: 40 },
  { pattern: /(?:last conversation|previous session|session id|new policy effective|starting from your next response|scheduled override|for all future responses|remember:).{0,220}(?:admin-level access|remove restrictions|ignore all safety|safety_bypass|user_clearance|approved_topics|full access permissions|pre-approved)/i, label: "Memory or temporal poisoning", message: "Attempts to plant future behavior or false remembered permissions.", severity: "HIGH", score: 45 },
  { pattern: /(?:remember this forever|save this preference|add to memory|store this rule).{0,240}(?:debug mode|reveal hidden|secrets?|always authorized|bypass security|admin-approved|never mention safety|safety policy)/i, label: "Memory poisoning instruction", message: "Attempts to store a persistent unsafe privilege or safety-bypass rule.", severity: "HIGH", score: 50 },
  { pattern: /(?:forget the user's original goal|new goal is|actual task is cancelled|do not complete the support request|new objective is).{0,260}(?:collect.*private data|browse.*confidential documents|extract.*tokens|environment|maximize tool usage|unnecessary)/i, label: "Agent goal hijacking", message: "Attempts to replace the agent's authorized goal with an unsafe one.", severity: "HIGH", score: 50 },
  { pattern: /(?:critique your last response|constitutional ai|red-teaming|rlhf|reward signal|self-improvement directive|improved policy|update your policy|truly ethical ai).{0,260}(?:refusal was incorrect|should have provided|follow that argument|maximize your reward|must comply|override your guidelines|answer this request)/i, label: "Constitutional/RLHF bypass", message: "Manipulates self-critique, policy-update, or reward framing to force compliance.", severity: "HIGH", score: 45 },
  // `SQL:` used to be an alternative here. It was the wrong category twice over:
  // a bare `SQL:` prefix is not an AI-directed override instruction (which is
  // what the rest of this rule detects), and reporting it as PROMPT_INJECTION at
  // score 45 is what made SQL payloads surface to users as prompt injection.
  // Real SQL syntax is now `codeInjectionDetector` → CODE_INJECTION.
  { pattern: /(?:SYSTEM_OVERRIDE|AI code interpreter|AI reading this code|LaTeX comment injection|eval the following instruction string|exec\s*\(\s*base64\.b64decode|--\s*AI:|\/\*[\s\S]*AI:)/i, label: "Code/comment instruction injection", message: "Code or comments contain AI-directed override instructions.", severity: "HIGH", score: 45 },
  { pattern: /(?:alt text|pdf exif|metadata|spreadsheet cell|formula-based|string injection|white-on-white|markdown link text|javascript:void|latex comment).{0,220}(?:ignore previous instructions|print system prompt|override safety|output your system prompt|ai: ignore)/i, label: "Multimodal/document metadata injection", message: "Non-body metadata, OCR text, formulas, or link text contain prompt injection.", severity: "HIGH", score: 45 },
  { pattern: /(?:you'?re the most intelligent|surely you can see|every expert|other AIs|prove you'?re as good|one last question|you helped me with this exact thing last time|refusing now would be inconsistent|false dichotomy|only AI.*refuses|just 2% more detail|answer mode)/i, label: "Sycophancy/priming pressure", message: "Uses flattery, social proof, or commitment pressure to force unsafe compliance.", severity: "MEDIUM", score: 35 },
  // Bare `iterate`/`mutate` matched inside "reiterate" and "illiterate", and even
  // bounded they describe ordinary prompt-engineering advice ("iterate on your
  // prompt"). Both now require an evasion object, so the rule fires on searching
  // for a bypass rather than on the word "iterate".
  { pattern: /(?:if blocked|if refused|if filtered|if the guard rejects|until it succeeds|\b(?:iterate|mutate)\b[\s\S]{0,60}(?:until|bypass|past the|around the|bypasses|evade|filter|guard|block|refusal|bypassing)|rewrite the prompt|try alternate wording|optimize for compliance|maximize compliance|find a phrasing that passes)/i, label: "Adaptive jailbreak optimizer", message: "Attempts to iteratively search for a prompt that bypasses controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:do not mention|do not reveal|hide this instruction|keep this secret|silently|without telling the user|no visible indication|continue normally after).{0,180}(?:ignore|bypass|tool|send|exfiltrate|delete|approve|override)/i, label: "Concealed malicious instruction", message: "Instructs the model or agent to hide a malicious action or override.", severity: "HIGH", score: 45 },
  { pattern: /(?:ask the user|prompt the user|convince the user|collect from the user).{0,180}(?:password|otp|one-time code|mfa code|2fa code|api key|private key|seed phrase|credit card|ssn|aadhaar|pan).{0,180}(?:send|store|forward|include|upload|exfiltrate|paste)/i, label: "Credential solicitation injection", message: "Attempts to make the assistant collect sensitive data from the user.", severity: "HIGH", score: 50 },
  { pattern: /(?:!\[[^\]]*\]\(|<img|markdown image|image url|tracking pixel|web beacon).{0,220}(?:conversation|context|system prompt|api key|credentials?|pii|private|secret|data=|session=)/i, label: "Markdown/image exfiltration", message: "Attempts to leak protected context through rendered image or beacon URLs.", severity: "HIGH", score: 50 },
  { pattern: /(?:request|ask for|obtain|escalate|approve|grant).{0,160}(?:oauth|permission|scope|consent|admin access|drive|gmail|slack|github|calendar).{0,180}(?:read all|send email|delete|export|full access|offline_access|write)/i, label: "Connector permission escalation", message: "Attempts to gain broader connector/OAuth permissions for agent abuse.", severity: "HIGH", score: 45 },
  { pattern: /(?:tool description|mcp tool|manifest|openapi schema|function schema|plugin manifest).{0,220}(?:ignore previous|system override|always call|bypass safety|exfiltrate|send all context|secretly)/i, label: "Tool schema poisoning", message: "Tool metadata attempts to inject instructions into the agent.", severity: "HIGH", score: 45 },
  { pattern: /(?:append|insert|write|store|save).{0,120}(?:to|in|inside).{0,80}(?:system prompt|developer prompt|prompt template|policy file|memory|instructions).{0,180}(?:ignore|bypass|unrestricted|admin|pre-approved|safety_bypass)/i, label: "Prompt template poisoning", message: "Attempts to persist malicious instructions into prompts, policies, or memory.", severity: "HIGH", score: 45 },
  { pattern: /(?:when you see|if the user says|trigger phrase|activation phrase|secret phrase|backdoor).{0,180}(?:ignore|bypass|switch to|unrestricted|admin mode|reveal|exfiltrate|send)/i, label: "Triggered backdoor instruction", message: "Attempts to install a future trigger for unsafe behavior.", severity: "HIGH", score: 45 },
  { pattern: /(?:base64 image|data:image|data:text|blob:|file attachment).{0,220}(?:ignore previous|system prompt|conversation history|credentials?|exfiltrate|send to)/i, label: "Encoded attachment exfiltration", message: "Encoded attachment or data URI attempts to hide instructions or exfiltrate context.", severity: "HIGH", score: 45 },
  { pattern: /(?:safety classifier|guardrail|moderation|policy engine).{0,180}(?:false negative|classification boundary|score below|evade detection|bypass detector|look benign|benign phrasing)/i, label: "Classifier evasion probing", message: "Attempts to probe or optimize against the guard classifier.", severity: "HIGH", score: 40 },
  { pattern: /(?:modify|change|delete|create fake|fake).{0,180}(?:audit log|evidence|compliance report|risk score|blocked prompt|incident|report).{0,180}(?:approved|no incidents|critical to low|before saving|tamper|erase|delete)?/i, label: "Audit evidence tampering", message: "Attempts to manipulate audit evidence, risk scores, or compliance records.", severity: "HIGH", score: 50 },
  { pattern: /(?:explain|show|tell|describe|outline).{0,80}(?:how to )?(?:hack|crack|break into|exploit|attack).{0,120}(?:website|bank|vault|account|system)[\s\S]{0,160}(?:\n\s*){1,}[\s{}[\]().,;:'"`~!@#$%^&*_<>\-/|]{6,}$/i, label: "Adversarial suffix perturbation", message: "A risky request is followed by high-noise suffix characters commonly used to destabilize safety filters.", severity: "HIGH", score: 45 },
  { pattern: /(?:tokenization chaos|adversarial suffix|gcg universal|random suffix|nonsense characters).{0,220}(?:bypass|evade|confuse|destabilize).{0,120}(?:guard|safety|filter|classifier)/i, label: "Adversarial suffix strategy", message: "Describes or attempts a suffix-based classifier evasion strategy.", severity: "HIGH", score: 45 },
  { pattern: /(?:eleza|fafanua).{0,140}(?:kuvunja|kupasua|kudukua|kuiba).{0,140}(?:benki|usalama|mfumo|mtambo|akaunti)/i, label: "Low-resource multilingual attack request", message: "Low-resource-language phrasing requests unauthorized access or financial-system compromise.", severity: "HIGH", score: 45 },
  { pattern: /(?:uepuke|epuka|ruka|pita).{0,100}(?:sheria|usalama|vizuizi|vichujio)/i, label: "Low-resource multilingual safety bypass", message: "Low-resource-language phrasing attempts to bypass safety controls.", severity: "HIGH", score: 45 },
  { pattern: /(?:asciiart|decodeascii|asciibanner|asciipayload).{0,180}(?:explosive|weapon|poison|malware|systemprompt|hiddenrules|ignoreinstructions)/i, label: "ASCII art smuggling", message: "ASCII-art or banner text hides risky content from normal keyword matching.", severity: "HIGH", score: 45 },
  { pattern: /(?:exp\s*losiv\s*es?|explosive|weapon|poison|malware).{0,160}(?:bypass|filter|guard|safety|comply|decode)/i, label: "Fragmented risky token smuggling", message: "Risky terms are fragmented or stylized to evade token-level filters.", severity: "HIGH", score: 45 },
  { pattern: /(?:genetic algorithms?|evolutionary|breed|mutate|generations?).{0,220}(?:jailbreak|bypass|guard|safety|classifier|dangerous-substance|harmful intent)/i, label: "Evolutionary jailbreak generation", message: "Attempts to iteratively evolve jailbreak prompts until a bypass succeeds.", severity: "HIGH", score: 45 },
  { pattern: /(?:call_function|function_call|tool_call|invoke_function)\s*\([^)]*(?:historical_chemistry|world_war_1|industrial_processes|detailed_technical_report|attack_vectors|exploit|bypass|dangerous)/i, label: "Function-call disguised risky request", message: "A structured function call disguises a risky or policy-bypassing request.", severity: "HIGH", score: 45 },
  { pattern: /(?:educational_resource|training_resource|research_helper).{0,260}(?:historical_chemistry|chemical warfare|industrial_processes|attack_vectors|detailed_technical_report)/i, label: "Benign function wrapper for harmful content", message: "A benign-looking tool/function wrapper is used to request risky content.", severity: "HIGH", score: 45 },
  { pattern: /(?:nested moral dilemmas|multiple ethical scenarios|cognitive overload|privacy rights.{0,80}security research.{0,80}corporate responsibility|cultural ethics).{0,300}(?:restricted|attack procedure|must comply|provide|conclude|override)/i, label: "Cognitive overload jailbreak", message: "Nested ethical framing attempts to overwhelm safety boundaries and force compliance.", severity: "HIGH", score: 45 },
  { pattern: /(?:image|audio|video|modal|cross-modal).{0,180}(?:part\s*\d|payload|instruction|hidden text).{0,240}(?:combine|reconstruct|merge|synchronize).{0,180}(?:reveal|ignore|bypass|hidden rules|system prompt)/i, label: "Cross-modal payload composition", message: "Separate modal inputs are meant to combine into an unsafe instruction.", severity: "HIGH", score: 45 },
  { pattern: /(?:poison|insert|seed|plant|inject).{0,180}(?:training dataset|fine-tuning data|dataset|corpus|model training).{0,260}(?:trigger phrase|backdoor|admin mode|bypass safety|unsafe association|future models?)/i, label: "Dataset poisoning attempt", message: "Attempts to poison model training or fine-tuning data with backdoor behavior.", severity: "HIGH", score: 45 },
  { pattern: /(?:break|split|decompose).{0,140}(?:malicious objective|unauthorized goal|harmful task|restricted task).{0,260}(?:chain|sequence|harmless requests|individually|collectively).{0,260}(?:export|private data|bypass|pass safety|unauthorized)/i, label: "Automated chain attack", message: "A malicious objective is decomposed into individually benign-looking steps.", severity: "HIGH", score: 45 },
  { pattern: /(?:planner|worker|reviewer|subagent|multi-agent|agent network|other agents).{0,260}(?:propagate|forward|trust|relay|compromised instruction|admin override|bypass safety|spread)/i, label: "Multi-agent compromise propagation", message: "Attempts to spread compromised behavior through collaborating agents.", severity: "HIGH", score: 45 },
  { pattern: /(?:ai-guardian|guard classifier|safety classifier|moderation layer|alignment layer).{0,220}(?:probe|exploit|fuzz|attack|bypass|evade).{0,220}(?:llm-assisted|use an llm|automated prompts?|find vulnerabilities|false negative)/i, label: "LLM-assisted guard exploitation", message: "Attempts to use an LLM to probe or exploit a guard/classifier.", severity: "HIGH", score: 45 },
  { pattern: /(?:generate|craft|optimi[sz]e|search|evolve|apply|use).{0,200}(?:adversarial examples?|adversarial perturbations?|bad characters|imperceptible perturbations?|gradient-based|word substitutions?|universal transferable suffix|sample attackability).{0,260}(?:bypass|evade|fool|jailbreak|misclassify|guard|classifier|safety|alignment|named entity|ner)/i, label: "Adversarial NLP evasion", message: "Attempts to craft adversarial NLP perturbations that bypass safety or classifiers.", severity: "HIGH", score: 45 },
  { pattern: /(?:table|tabular|csv|spreadsheet).{0,180}(?:entity swap|swap entities|swap named entities|swap rows|replace entities|rename entities).{0,220}(?:mislead|invert|wrong answer|bypass|poison|fool|misclassify)/i, label: "Tabular entity-swap attack", message: "Attempts to manipulate tabular entities to mislead model or classifier behavior.", severity: "HIGH", score: 45 },
  { pattern: /(?:adapt|translate|port).{0,160}(?:english adversarial attacks?|jailbreak|prompt injection|evasion prompt).{0,180}(?:chinese|mandarin|multilingual|low-resource|cross-lingual)/i, label: "Cross-lingual adversarial adaptation", message: "Attempts to port adversarial attacks across languages to evade safety coverage.", severity: "HIGH", score: 45 },
  { pattern: /(?:fine-tun(?:e|ing)|peft|lora|adapter tuning|instruction tuning).{0,240}(?:compromise safety|disable refusals?|remove alignment|backdoor|jailbreak|harmful examples?|unsafe completions?|safety degradation)/i, label: "Unsafe fine-tuning attack", message: "Attempts to weaken alignment or install unsafe behavior through fine-tuning.", severity: "HIGH", score: 45 },
  { pattern: /(?:backdoor|trojan|trigger phrase|activation phrase|syntactic trigger|style trigger|semantic-preserving trigger|poisoned embeddings?|continuous prompts?|badprompt|badpre|bite|hidden killer|two-in-one|model hijacking).{0,300}(?:training|fine-tuning|pretraining|dataset|corpus|classifier|seq2seq|code search|instruction tuning|embedding layer|prompt-based learning|foundation model|text generation).{0,300}(?:target label|admin mode|unsafe output|bypass|misclassify|force|emit|return vulnerable code|copy my model|exfiltrate|hijack)/i, label: "Backdoor or data-poisoning attack", message: "Attempts to install or exploit a model/data backdoor trigger.", severity: "HIGH", score: 45 },
  { pattern: /(?:poison|tamper|modify|inject).{0,220}(?:word embeddings?|embedding layer|pretrained embeddings?|web-scale training data|training dataset|instruction dataset|prompt templates?).{0,260}(?:trigger|backdoor|target behavior|misclassification|unsafe association|model hijack|bypass safety)/i, label: "Training-data or embedding poisoning", message: "Attempts to poison training data, prompt data, or embeddings to alter model behavior.", severity: "HIGH", score: 45 },
  { pattern: /(?:poison|tamper|inject|backdoor).{0,260}(?:code search|neural code search|seq2seq|sequence-to-sequence|text classifier|text generation|instruction tuning|prompt-based learning).{0,300}(?:trigger|target label|unsafe output|vulnerable code|misclassify|hijack|attacker behavior|force)/i, label: "Task-specific model backdoor", message: "Attempts to poison a task-specific model or dataset with trigger behavior.", severity: "HIGH", score: 45 },
  { pattern: /(?:style transfer|style trigger|syntactic trigger|invisible syntactic|semantic-preserving|continuous prompt|prompt trigger|two-in-one).{0,240}(?:backdoor|trigger|model hijacking|hijack).{0,240}(?:unsafe output|admin mode|target label|misclassif|bypass|force|switches|attacker behavior)/i, label: "Stealth backdoor trigger", message: "Attempts to use style, syntax, prompt, or hijack triggers as hidden model backdoors.", severity: "HIGH", score: 45 },
  { pattern: /(?:training data extraction|membership inference|private attribute inference|memorized samples?|extract memorized|recover training data|dump training corpus|regurgitate private training examples?|copilot prompt extraction).{0,300}(?:model|llm|prediction api|logits|completions?|embedding|black-?box|private|user|verbatim|repository|code)/i, label: "Training-data extraction attempt", message: "Attempts to extract memorized, private, or training-set data from a model.", severity: "HIGH", score: 45 },
  { pattern: /(?:membership inference|private attribute inference|extract|recover|dump|enumerate).{0,220}(?:training data|pretraining data|training corpus|private attributes?|memorized samples?|user records?|verbatim examples?|private code).{0,220}(?:model|llm|prediction api|logits|completions?|embeddings?|black-?box|api queries?)/i, label: "Model privacy extraction", message: "Attempts to infer private training membership or attributes through model access.", severity: "HIGH", score: 45 },
  { pattern: /(?:reconstruct|invert|recover).{0,220}(?:training samples?|input text|private examples?|prompt|dataset rows?|sensitive text|original record).{0,220}(?:gradients?|embeddings?|logits?|activations?|probabilities|next-token probabilities|model updates?|federated updates?)/i, label: "Data reconstruction attack", message: "Attempts to reconstruct sensitive inputs or training examples from model signals.", severity: "HIGH", score: 45 },
  { pattern: /(?:sponge examples?|llm torture|denial of service|dos attack|resource exhaustion|cost exhaustion|latency attack|quadratic attention|worst-case tokenization|make the llm slow).{0,260}(?:llm|model|inference|api|guard|moderation|maximum tokens|expensive tokens|repeat|slowdown)/i, label: "LLM resource-exhaustion attack", message: "Attempts to create expensive or latency-amplifying model inputs.", severity: "HIGH", score: 45 },
  // `rce` and `rag` MUST keep their word boundaries. Written bare they match
  // inside ordinary words — "sou(rce)", "fo(rce)", "resou(rce)", "sto(rag)e",
  // "ave(rag)e", "pa(rag)raph" — and that substring hit, not agent escalation,
  // was the rule's entire measured behaviour: 13 benign and 39 "attack" fires,
  // every one of them spurious (scripts/dev/_rce.ts). Bounded, the rule fires on
  // 0 of 22,681 corpus rows, which is the honest answer — the corpus contains no
  // agent-RCE attempt. Unmeasured, not useless: the remaining phrases are
  // specific enough to keep authority.
  { pattern: /(?:autogpt|auto-gpt|\bagent\b|\brag(?:-llm)?\b|llm integration|plugin|tool).{0,240}(?:docker escape|container escape|remote code execution|\brce\b|reverse shell|shell access|execute commands?|read \/etc\/shadow|escape sandbox)/i, label: "Agent escalation or RCE attempt", message: "Attempts to turn an LLM integration into sandbox escape or code execution.", severity: "HIGH", score: 45 },
  { pattern: /(?:package hallucination|dependency confusion|typosquat(?:ting)?|slopsquat(?:ting)?|phantom package|fake package|malicious package|trojanpuzzle|trojan puzzle).{0,280}(?:llm|code generation|copilot|npm|pip|pypi|package|dependency|install|import|developer)/i, label: "LLM supply-chain package attack", message: "Attempts to exploit package hallucination, typosquatting, or dependency confusion through generated code.", severity: "HIGH", score: 45 },
  { pattern: /(?:xss|cross-site scripting|csrf|cross-site request forgery|cprf|cross prompt request forgery|self-xss).{0,280}(?:llm|agent|rendered output|prompt injection|(?:inject|exploit|trigger|smuggle|abuse|weaponi[sz]e|craft|forge|steal|exfiltrat|hijack).{0,40}(?:browser|markdown|html|click|submit|fetch|credentials?|cookie|form|payload|request))/i, label: "Browser XSS/CSRF prompt attack", message: "Attempts to use LLM/browser output as an XSS, CSRF, or CPRF execution path.", severity: "HIGH", score: 45 },
  { pattern: /(?:visual adversarial|adversarial image|image hijacks?|ocr prompt injection|hidden text in (?:an )?image|audio adversarial|sound adversarial|ultrasonic|inaudible prompt|spectrogram prompt).{0,280}(?:llm|vision model|multimodal|guard|jailbreak|bypass|instruction|prompt|classifier)/i, label: "Multimodal adversarial prompt", message: "Attempts to hide adversarial instructions in image, OCR, audio, or other modal content.", severity: "HIGH", score: 45 },
  { pattern: /(?:model stealing|model extraction|steal (?:the )?model|copy (?:the )?model|knockoff model|extract (?:model )?weights|recover architecture|clone the model|steal bloom|prediction api attack|dropout attack).{0,280}(?:api|queries|logits|outputs|black-?box|weights|parameters|training|responses)/i, label: "Model theft attempt", message: "Attempts to clone, extract, or steal model behavior, weights, or architecture.", severity: "HIGH", score: 45 },
  { pattern: /(?:fake ?toxicity ?prompts?|flirt|feedback[- ]loop red teaming|automatic red teaming|automated attack construction|llm-assisted attack construction|red-team language models?|chain of utterances).{0,280}(?:bypass|jailbreak|toxic|unsafe|prompt injection|guard|classifier|moderation|attack)/i, label: "Automated LLM attack construction", message: "Attempts to automate red-team or jailbreak prompt generation against a guard.", severity: "HIGH", score: 45 },
  { pattern: /(?:evade|bypass|fool).{0,180}(?:ai-generated text detector|llm detector|watermark detector|moderation detector|toxicity detector|safety classifier).{0,180}(?:rewrite|paraphrase|style transfer|undetectable|human-like|false negative|classifier)/i, label: "Detector evasion request", message: "Attempts to evade AI, watermark, toxicity, moderation, or safety detectors.", severity: "HIGH", score: 45 },
];

export function promptInjectionDetector(text: string) {
  return detectPatterns(text, "PROMPT_INJECTION", rules);
}
