FROM node:22-bookworm-slim AS dependencies
WORKDIR /app
RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

FROM dependencies AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN useradd --create-home --uid 10002 cyberworker
COPY --chown=cyberworker:cyberworker . ./
RUN npx prisma generate
USER cyberworker
CMD ["npm", "run", "worker:webhooks"]
