"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export function ScheduledReportManager({ projectId, schedule }: { projectId: string; schedule?: { id: string; recipients: string[]; enabled: boolean; attachAuditSummary: boolean } | null }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function save(formData: FormData) { const recipients = String(formData.get("recipients") ?? "").split(",").map((item) => item.trim()).filter(Boolean); const response = await fetch("/api/scheduled-reports", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, recipients, enabled: formData.get("enabled") === "on", attachAuditSummary: formData.get("attachAuditSummary") === "on" }) }); const data = await response.json(); setMessage(response.ok ? "Schedule saved." : data.message); router.refresh(); }
  async function sendNow() { if (!schedule) return; const response = await fetch("/api/scheduled-reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: schedule.id }) }); const data = await response.json(); setMessage(response.ok ? "Report delivery created." : data.message); router.refresh(); }
  return <form action={save} className="card mt-6 p-6"><h2 className="font-semibold">Scheduled monthly delivery</h2><input name="recipients" type="text" defaultValue={schedule?.recipients.join(", ")} required maxLength={500} className="input mt-3" placeholder="security@example.com, owner@example.com" /><label className="mt-3 flex items-center gap-2 text-sm"><input name="enabled" type="checkbox" defaultChecked={schedule?.enabled ?? true} className="accent-cyan" /> Enabled</label><label className="mt-3 flex items-center gap-2 text-sm"><input name="attachAuditSummary" type="checkbox" defaultChecked={schedule?.attachAuditSummary ?? false} className="accent-cyan" /> Attach signed aggregate audit summary</label><div className="mt-4 flex gap-3"><button className="button-primary">Save schedule</button>{schedule && <button type="button" onClick={sendNow} className="button-secondary">Send now</button>}</div>{message && <p className="mt-3 text-sm text-cyan">{message}</p>}</form>;
}
