export function buildA(uid, SOTER_CRED) {
  const nChat = { id: uid(), name: 'When chat message received', type: '@n8n/n8n-nodes-langchain.chatTrigger', typeVersion: 1.1, position: [-1700, 300], webhookId: 'soter-saas-chat', parameters: { responseMode: 'responseNode', options: {} } };
  const nInputGuard = { id: uid(), name: 'Soter Input Guard', type: 'n8n-nodes-soterai.soterGuard', typeVersion: 2, position: [-1460, 300], credentials: { soterApi: SOTER_CRED }, parameters: { action: 'inputGuard', inputText: '={{ $json.chatInput }}', sessionId: '={{ $json.sessionId }}', allowedTopics: 'billing, subscriptions, invoices, sso login, api errors, csv export, bug reports, feature requests, account help', systemPromptContext: 'You are AcmeCloud SaaS support for billing, login, API, exports, bug reports and account help.', onThreat: 'BLOCK', detectionEngine: 'AUTO', advancedOptions: {} } };
  const nIncident = { id: uid(), name: 'Security Incident Log', type: 'n8n-nodes-base.code', typeVersion: 2, position: [-1220, 60], parameters: { mode: 'runOnceForEachItem', jsCode: "const g=$input.first().json;const c=$('When chat message received').first().json;return [{json:{event:'soter_block',sessionId:c.sessionId??null,chatInput:c.chatInput??null,verdictCode:g.verdictCode??null,riskLevel:g.riskLevel??null,riskScore:g.riskScore??null,timestamp:new Date().toISOString()}}];" } };
  const nBlocked = { id: uid(), name: 'Respond (Blocked)', type: '@n8n/n8n-nodes-langchain.chat', typeVersion: 1, position: [-980, 60], parameters: { message: '=Blocked by SoterAI Security. Your message looked like a prompt-injection or policy violation, so it was stopped before the AI agent. Verdict: {{ $json.verdictCode ?? "CONTENT_BLOCKED" }} | Risk: {{ $json.riskLevel ?? "n/a" }}. Please rephrase your support question.', options: {} } };
  const nPii = { id: uid(), name: 'PII Redactor', type: 'n8n-nodes-soterai.soterGuard', typeVersion: 2, position: [-1220, 300], credentials: { soterApi: SOTER_CRED }, parameters: { action: 'piiRedactor', piiText: '={{ $json.safeText }}', detectionEngine: 'AUTO', advancedOptions: {} } };
  const nNorm = { id: uid(), name: 'Normalize Request', type: 'n8n-nodes-base.code', typeVersion: 2, position: [-980, 300], parameters: { mode: 'runOnceForEachItem', jsCode: "const chat=$('When chat message received').first().json;const guard=$('Soter Input Guard').first().json;const pii=$input.first().json;const clean=pii.safeText??pii.redactedText??pii.outputText??guard.safeText??chat.chatInput;return [{json:{sessionId:chat.sessionId??null,chatInput:chat.chatInput??'',safeText:guard.safeText??chat.chatInput??'',cleanText:clean,verdictCode:guard.verdictCode??null,riskLevel:guard.riskLevel??null}}];" } };
  return { nChat, nInputGuard, nIncident, nBlocked, nPii, nNorm };
}
