"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function SupportTicketForm({ projects }: { projects: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function submit(formData: FormData) { const response = await fetch("/api/phase8/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId: formData.get("projectId") || undefined, category: formData.get("category"), priority: formData.get("priority"), subject: formData.get("subject"), message: formData.get("message"), redactedContext: formData.get("redactedContext") || undefined }) }); const result = await response.json(); if (response.ok) { router.push("/dashboard/support"); router.refresh(); } else setMessage(result.message); }
  return <form action={submit} className="grid gap-4"><select className="input" name="category"><option value="INTEGRATION_HELP">Integration help</option><option value="BILLING">Billing</option><option value="FALSE_POSITIVE">False positive</option><option value="MISSED_DETECTION">Missed detection</option><option value="RAG_ISSUE">RAG issue</option><option value="WEBHOOK_ISSUE">Webhook issue</option><option value="ENTERPRISE_SETUP">Enterprise setup</option><option value="SECURITY_CONCERN">Security concern</option></select><select className="input" name="projectId"><option value="">No project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select><select className="input" name="priority"><option value="NORMAL">Normal</option><option value="LOW">Low</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select><input className="input" name="subject" required minLength={4} placeholder="Subject" /><textarea className="input min-h-36" name="message" required minLength={10} placeholder="Describe the issue. Remove credentials and raw secrets." /><textarea className="input min-h-24" name="redactedContext" placeholder="Optional redacted example or request ID" /><button className="button-primary">Create ticket</button>{message && <p className="text-sm text-red-300">{message}</p>}</form>;
}
