"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function IncidentForm() { const router = useRouter(); const [message, setMessage] = useState(""); async function submit(formData: FormData) { const response = await fetch("/api/ops/incidents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: formData.get("title"), summary: formData.get("summary"), impact: formData.get("impact"), affectedComponents: String(formData.get("components") ?? "").split(",").map(v => v.trim()).filter(Boolean), public: formData.get("public") === "on" }) }); const result = await response.json(); setMessage(response.ok ? `Incident ${result.slug} created.` : result.message); router.refresh(); }
  return <form action={submit} className="grid gap-3"><input className="input" name="title" required placeholder="Incident title" /><textarea className="input" name="summary" required minLength={10} placeholder="Public-safe summary without sensitive internals" /><input className="input" name="components" placeholder="Guard API, Dashboard" /><select className="input" name="impact"><option value="MINOR">Minor</option><option value="MAJOR">Major</option><option value="CRITICAL">Critical</option><option value="NONE">None</option></select><label className="text-sm"><input className="mr-2" type="checkbox" name="public" />Publish on status page</label><button className="button-primary">Open incident</button>{message && <p className="text-sm text-cyan">{message}</p>}</form>; }

export function FeedbackReviewForm({ feedbackId }: { feedbackId: string }) { const router = useRouter(); const [message, setMessage] = useState(""); async function submit(formData: FormData) { const response = await fetch("/api/ops/feedback-review", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ feedbackId, status: formData.get("status"), detector: formData.get("detector") || undefined, datasetVersion: formData.get("datasetVersion") || undefined, redactedExample: formData.get("redactedExample") || undefined, tuningSuggestion: formData.get("tuningSuggestion") || undefined }) }); setMessage(response.ok ? "Reviewed" : "Failed"); router.refresh(); }
  return <form action={submit} className="mt-3 grid gap-2"><select className="input !py-2" name="status"><option value="ACCEPTED">Accept</option><option value="REJECTED">Reject</option><option value="NEEDS_MORE_INFO">Needs info</option></select><input className="input !py-2" name="detector" placeholder="Detector" /><input className="input !py-2" name="datasetVersion" placeholder="Dataset version" /><textarea className="input min-h-20 !py-2" name="redactedExample" placeholder="Redacted example only" /><input className="input !py-2" name="tuningSuggestion" placeholder="Tuning suggestion" /><button className="button-primary !py-2">Save review</button>{message && <p className="text-xs text-cyan">{message}</p>}</form>; }
