"use client";
import { useState } from "react";

export function PilotRequestForm({ organizationId }: { organizationId?: string }) {
  const [message, setMessage] = useState("");
  async function submit(formData: FormData) {
    const payload = { organizationId, companyName: formData.get("companyName"), contactName: formData.get("contactName"), contactEmail: formData.get("contactEmail"), useCase: formData.get("useCase"), chatbotType: formData.get("chatbotType"), usesRag: formData.get("usesRag") === "on", expectedMonthlyMessages: Number(formData.get("expectedMonthlyMessages")), securityRequirements: formData.get("securityRequirements"), needsSso: formData.get("needsSso") === "on", needsScim: formData.get("needsScim") === "on", deploymentPreference: formData.get("deploymentPreference") };
    const response = await fetch("/api/ops/pilot", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); setMessage(response.ok ? `Pilot request ${result.id} received.` : result.message);
  }
  return <form action={submit} className="grid gap-4 md:grid-cols-2"><input className="input" name="companyName" required placeholder="Company name" /><input className="input" name="contactName" required placeholder="Contact name" /><input className="input" name="contactEmail" type="email" required placeholder="Work email" /><input className="input" name="chatbotType" required placeholder="Chatbot or agent type" /><input className="input" name="expectedMonthlyMessages" type="number" min="1" required placeholder="Expected monthly messages" /><select className="input" name="deploymentPreference" defaultValue="cloud"><option value="cloud">Cloud</option><option value="self-hosted">Self-hosted</option><option value="hybrid">Hybrid</option></select><textarea className="input min-h-28 md:col-span-2" name="useCase" required minLength={20} placeholder="Describe the use case and data flow" /><textarea className="input min-h-28 md:col-span-2" name="securityRequirements" required minLength={10} placeholder="Security, compliance, and integration requirements" /><div className="flex flex-wrap gap-5 text-sm md:col-span-2"><label><input className="mr-2" type="checkbox" name="usesRag" />Uses RAG</label><label><input className="mr-2" type="checkbox" name="needsSso" />SAML SSO</label><label><input className="mr-2" type="checkbox" name="needsScim" />SCIM</label></div><button className="button-primary md:col-span-2">Request enterprise pilot</button>{message && <p className="text-sm text-cyan md:col-span-2">{message}</p>}</form>;
}
