// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/abuse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/abuse">> = Specific
  const handler = {} as typeof import("../../app/admin/abuse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/admin/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/classifier-evals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/classifier-evals">> = Specific
  const handler = {} as typeof import("../../app/admin/classifier-evals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/detection-quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/detection-quality">> = Specific
  const handler = {} as typeof import("../../app/admin/detection-quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/growth/metrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/growth/metrics">> = Specific
  const handler = {} as typeof import("../../app/admin/growth/metrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/kms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kms">> = Specific
  const handler = {} as typeof import("../../app/admin/kms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ml/datasets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ml/datasets">> = Specific
  const handler = {} as typeof import("../../app/admin/ml/datasets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ml/deployments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ml/deployments">> = Specific
  const handler = {} as typeof import("../../app/admin/ml/deployments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ml/evaluations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ml/evaluations">> = Specific
  const handler = {} as typeof import("../../app/admin/ml/evaluations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ml/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ml">> = Specific
  const handler = {} as typeof import("../../app/admin/ml/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/ml/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ml/review">> = Specific
  const handler = {} as typeof import("../../app/admin/ml/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/organizations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/organizations">> = Specific
  const handler = {} as typeof import("../../app/admin/organizations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/privacy">> = Specific
  const handler = {} as typeof import("../../app/admin/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/production/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/production">> = Specific
  const handler = {} as typeof import("../../app/admin/production/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/redteam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/redteam">> = Specific
  const handler = {} as typeof import("../../app/admin/redteam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/siem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/siem">> = Specific
  const handler = {} as typeof import("../../app/admin/siem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/supply-chain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/supply-chain">> = Specific
  const handler = {} as typeof import("../../app/admin/supply-chain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../app/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system-health">> = Specific
  const handler = {} as typeof import("../../app/admin/system-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/threat-intel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/threat-intel">> = Specific
  const handler = {} as typeof import("../../app/admin/threat-intel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies">> = Specific
  const handler = {} as typeof import("../../app/case-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/case-studies/template/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/case-studies/template">> = Specific
  const handler = {} as typeof import("../../app/case-studies/template/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance/iso27001-readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/iso27001-readiness">> = Specific
  const handler = {} as typeof import("../../app/compliance/iso27001-readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance/owasp-llm-top-10/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/owasp-llm-top-10">> = Specific
  const handler = {} as typeof import("../../app/compliance/owasp-llm-top-10/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance/soc2-readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance/soc2-readiness">> = Specific
  const handler = {} as typeof import("../../app/compliance/soc2-readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact-sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-sales">> = Specific
  const handler = {} as typeof import("../../app/contact-sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agency/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agency/clients/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agency/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agency/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agency/clients/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agency/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agency/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agency/clients">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agency/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agency">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agency/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agency/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agency/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/agent-firewall/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/agent-firewall">> = Specific
  const handler = {} as typeof import("../../app/dashboard/agent-firewall/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/api-keys">> = Specific
  const handler = {} as typeof import("../../app/dashboard/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/badges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/badges">> = Specific
  const handler = {} as typeof import("../../app/dashboard/badges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/customer-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/customer-success">> = Specific
  const handler = {} as typeof import("../../app/dashboard/customer-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/detection-feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/detection-feedback">> = Specific
  const handler = {} as typeof import("../../app/dashboard/detection-feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise/audit">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/data-retention/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise/data-retention">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/data-retention/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/pilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise/pilot">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/pilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/scim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise/scim">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/scim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise/security">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/enterprise/sso/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/enterprise/sso">> = Specific
  const handler = {} as typeof import("../../app/dashboard/enterprise/sso/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/exports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/exports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/exports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/get-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/get-started">> = Specific
  const handler = {} as typeof import("../../app/dashboard/get-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/logs">> = Specific
  const handler = {} as typeof import("../../app/dashboard/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/onboarding/agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/onboarding/agency">> = Specific
  const handler = {} as typeof import("../../app/dashboard/onboarding/agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/onboarding/beta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/onboarding/beta">> = Specific
  const handler = {} as typeof import("../../app/dashboard/onboarding/beta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/onboarding/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/onboarding/enterprise">> = Specific
  const handler = {} as typeof import("../../app/dashboard/onboarding/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/onboarding">> = Specific
  const handler = {} as typeof import("../../app/dashboard/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/partner/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partner/clients">> = Specific
  const handler = {} as typeof import("../../app/dashboard/partner/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partner">> = Specific
  const handler = {} as typeof import("../../app/dashboard/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/partner/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/partner/resources">> = Specific
  const handler = {} as typeof import("../../app/dashboard/partner/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/policy">> = Specific
  const handler = {} as typeof import("../../app/dashboard/policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/privacy">> = Specific
  const handler = {} as typeof import("../../app/dashboard/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projects/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projects">> = Specific
  const handler = {} as typeof import("../../app/dashboard/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/rag/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/rag">> = Specific
  const handler = {} as typeof import("../../app/dashboard/rag/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/rag/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/rag/security">> = Specific
  const handler = {} as typeof import("../../app/dashboard/rag/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/redteam/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/redteam">> = Specific
  const handler = {} as typeof import("../../app/dashboard/redteam/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/reports/white-label/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/reports/white-label">> = Specific
  const handler = {} as typeof import("../../app/dashboard/reports/white-label/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/security/supply-chain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/security/supply-chain">> = Specific
  const handler = {} as typeof import("../../app/dashboard/security/supply-chain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/support/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/support/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/support">> = Specific
  const handler = {} as typeof import("../../app/dashboard/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/webhooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/webhooks">> = Specific
  const handler = {} as typeof import("../../app/dashboard/webhooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/data-retention/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-retention">> = Specific
  const handler = {} as typeof import("../../app/data-retention/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo-chatbot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo-chatbot">> = Specific
  const handler = {} as typeof import("../../app/demo-chatbot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/rag/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/rag">> = Specific
  const handler = {} as typeof import("../../app/demo/rag/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/red-team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/red-team">> = Specific
  const handler = {} as typeof import("../../app/demo/red-team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise">> = Specific
  const handler = {} as typeof import("../../app/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/pilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise/pilot">> = Specific
  const handler = {} as typeof import("../../app/enterprise/pilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/partners/agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partners/agency">> = Specific
  const handler = {} as typeof import("../../app/partners/agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playground">> = Specific
  const handler = {} as typeof import("../../app/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/responsible-disclosure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/responsible-disclosure">> = Specific
  const handler = {} as typeof import("../../app/responsible-disclosure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/security-status/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security-status/[slug]">> = Specific
  const handler = {} as typeof import("../../app/security-status/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../app/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subprocessors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subprocessors">> = Specific
  const handler = {} as typeof import("../../app/subprocessors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trust/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trust">> = Specific
  const handler = {} as typeof import("../../app/trust/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/actions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/actions">> = Specific
  const handler = {} as typeof import("../../app/api/admin/actions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/ml/datasets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ml/datasets">> = Specific
  const handler = {} as typeof import("../../app/api/admin/ml/datasets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/ml/evaluations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ml/evaluations">> = Specific
  const handler = {} as typeof import("../../app/api/admin/ml/evaluations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/ml/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ml/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/admin/ml/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/ml/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ml/models">> = Specific
  const handler = {} as typeof import("../../app/api/admin/ml/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/ml/review/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/ml/review/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/ml/review/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/process">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/webhooks/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/webhooks/process">> = Specific
  const handler = {} as typeof import("../../app/api/admin/webhooks/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/branding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/branding">> = Specific
  const handler = {} as typeof import("../../app/api/agency/branding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency/clients">> = Specific
  const handler = {} as typeof import("../../app/api/agency/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agency/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agency">> = Specific
  const handler = {} as typeof import("../../app/api/agency/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent-firewall/inspect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent-firewall/inspect">> = Specific
  const handler = {} as typeof import("../../app/api/agent-firewall/inspect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/api-keys/rotate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/api-keys/rotate">> = Specific
  const handler = {} as typeof import("../../app/api/api-keys/rotate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/api-keys/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api/api-keys/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/request-password-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/request-password-reset">> = Specific
  const handler = {} as typeof import("../../app/api/auth/request-password-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/signup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/signup">> = Specific
  const handler = {} as typeof import("../../app/api/auth/signup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/badge/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/badge/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/badge/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/badge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/badge">> = Specific
  const handler = {} as typeof import("../../app/api/badge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/activate">> = Specific
  const handler = {} as typeof import("../../app/api/billing/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/cancel">> = Specific
  const handler = {} as typeof import("../../app/api/billing/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/diagnostics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/diagnostics">> = Specific
  const handler = {} as typeof import("../../app/api/billing/diagnostics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/lifecycle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/lifecycle">> = Specific
  const handler = {} as typeof import("../../app/api/billing/lifecycle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/reactivate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/reactivate">> = Specific
  const handler = {} as typeof import("../../app/api/billing/reactivate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/data-deletion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/data-deletion">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/data-deletion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/data-retention/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/data-retention">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/data-retention/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/saml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/saml">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/saml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/scim-tokens/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/scim-tokens">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/scim-tokens/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/security/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/security">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/security/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enterprise/sso/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enterprise/sso">> = Specific
  const handler = {} as typeof import("../../app/api/enterprise/sso/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/events/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/events/stream">> = Specific
  const handler = {} as typeof import("../../app/api/events/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/exports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exports">> = Specific
  const handler = {} as typeof import("../../app/api/exports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guard/analyze/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guard/analyze">> = Specific
  const handler = {} as typeof import("../../app/api/guard/analyze/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guard/grounding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guard/grounding">> = Specific
  const handler = {} as typeof import("../../app/api/guard/grounding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guard/input/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guard/input">> = Specific
  const handler = {} as typeof import("../../app/api/guard/input/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/guard/output/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/guard/output">> = Specific
  const handler = {} as typeof import("../../app/api/guard/output/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/integrations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/integrations">> = Specific
  const handler = {} as typeof import("../../app/api/integrations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logs">> = Specific
  const handler = {} as typeof import("../../app/api/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/members/invite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/members/invite">> = Specific
  const handler = {} as typeof import("../../app/api/members/invite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding">> = Specific
  const handler = {} as typeof import("../../app/api/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/contact">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/feedback-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/feedback-review">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/feedback-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/incidents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/incidents">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/incidents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/onboarding/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/onboarding">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/onboarding/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/partner/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/partner">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/partner/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/pilot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/pilot">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/pilot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/support/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/support/messages">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/support/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/phase8/support/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/phase8/support">> = Specific
  const handler = {} as typeof import("../../app/api/phase8/support/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/badge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/badge">> = Specific
  const handler = {} as typeof import("../../app/api/projects/badge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/policy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/policy">> = Specific
  const handler = {} as typeof import("../../app/api/projects/policy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/chunks/acl/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/chunks/acl">> = Specific
  const handler = {} as typeof import("../../app/api/rag/chunks/acl/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/collections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/collections">> = Specific
  const handler = {} as typeof import("../../app/api/rag/collections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/documents/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/documents/review">> = Specific
  const handler = {} as typeof import("../../app/api/rag/documents/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/documents">> = Specific
  const handler = {} as typeof import("../../app/api/rag/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/rag/query/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/rag/query">> = Specific
  const handler = {} as typeof import("../../app/api/rag/query/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ready">> = Specific
  const handler = {} as typeof import("../../app/api/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/redteam/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/redteam/run">> = Specific
  const handler = {} as typeof import("../../app/api/redteam/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/pdf">> = Specific
  const handler = {} as typeof import("../../app/api/reports/pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports">> = Specific
  const handler = {} as typeof import("../../app/api/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scheduled-reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scheduled-reports">> = Specific
  const handler = {} as typeof import("../../app/api/scheduled-reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/Groups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/Groups/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/Groups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/Groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/Groups">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/Groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/ResourceTypes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/ResourceTypes">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/ResourceTypes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/Schemas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/Schemas">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/Schemas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/ServiceProviderConfig/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/ServiceProviderConfig">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/ServiceProviderConfig/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/Users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/Users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/Users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/scim/v2/Users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scim/v2/Users">> = Specific
  const handler = {} as typeof import("../../app/api/scim/v2/Users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/siem/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/siem">> = Specific
  const handler = {} as typeof import("../../app/api/siem/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sso/saml/acs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sso/saml/acs">> = Specific
  const handler = {} as typeof import("../../app/api/sso/saml/acs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sso/saml/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sso/saml/login">> = Specific
  const handler = {} as typeof import("../../app/api/sso/saml/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sso/saml/metadata/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sso/saml/metadata">> = Specific
  const handler = {} as typeof import("../../app/api/sso/saml/metadata/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sso/saml/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sso/saml/test">> = Specific
  const handler = {} as typeof import("../../app/api/sso/saml/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/deliveries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/deliveries">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/deliveries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/replay/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/replay">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/replay/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/rotate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/rotate">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/rotate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/webhooks/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/test">> = Specific
  const handler = {} as typeof import("../../app/api/webhooks/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/badge.js/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/badge.js">> = Specific
  const handler = {} as typeof import("../../app/badge.js/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
