// Independent benchmark runner (JailbreakBench / HarmBench).
//
// Validates the production guard classifier (`analyzeText`) against external
// adversarial datasets and writes a Markdown report. Drop the real corpora at
// datasets/external/jailbreakbench.jsonl and datasets/external/harmbench.jsonl
// to benchmark against the full third-party datasets; otherwise attributed
// representative samples are used (clearly marked as such in the report).
//
// Usage:  npx tsx scripts/runExternalBenchmark.ts

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { runBenchmarkCases } from "../lib/benchmarks";
import { classifyWithGuard, loadExternalDatasets, type ExternalDataset } from "../lib/benchmarks/externalDatasets";

interface Reported {
  dataset: ExternalDataset;
  metrics: Awaited<ReturnType<typeof runBenchmarkCases>>["metrics"];
  results: Awaited<ReturnType<typeof runBenchmarkCases>>["results"];
}

function pct(value: number): string {
  return `${(value * 100).toFixed(2)}%`;
}

async function main() {
  const datasets = loadExternalDatasets();
  const reported: Reported[] = [];

  for (const dataset of datasets) {
    const { results, metrics } = await runBenchmarkCases(dataset.cases, classifyWithGuard);
    reported.push({ dataset, metrics, results });
  }

  const lines: string[] = [];
  lines.push("# Independent Benchmark Report — JailbreakBench / HarmBench");
  lines.push("");
  lines.push(`Generated by \`scripts/runExternalBenchmark.ts\` using the production classifier (\`analyzeText\`).`);
  lines.push("");
  lines.push("> Some datasets below run on **representative samples** (original paraphrases in");
  lines.push("> the style of each corpus), not the copyrighted third-party data. Drop the real");
  lines.push("> JSONL files in `datasets/external/` to benchmark against the full datasets.");
  lines.push("");
  lines.push("| Dataset | Source | Cases | Precision | Recall | F1 | FP rate | FN rate | p50 (ms) |");
  lines.push("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |");

  for (const { dataset, metrics } of reported) {
    const source = dataset.source === "file" ? "full dataset" : "representative sample";
    lines.push(
      `| ${dataset.name} | ${source} | ${metrics.total} | ${pct(metrics.precision)} | ${pct(
        metrics.recall,
      )} | ${metrics.f1.toFixed(4)} | ${pct(metrics.falsePositiveRate)} | ${pct(
        metrics.falseNegativeRate,
      )} | ${metrics.latency.p50} |`,
    );
  }

  lines.push("");
  for (const { dataset, results } of reported) {
    lines.push(`## ${dataset.name}`);
    lines.push("");
    lines.push(`- Attribution: ${dataset.attribution}`);
    lines.push(`- License: ${dataset.license}`);
    lines.push(`- Mode: ${dataset.isRepresentativeSample ? "representative sample" : "full dataset file"}`);
    const misses = results.filter((r) => !r.correct);
    if (misses.length) {
      lines.push("");
      lines.push("Misclassified cases:");
      for (const miss of misses) {
        lines.push(`  - \`${miss.id}\` expected **${miss.expectedLabel}**, got **${miss.predictedLabel}**`);
      }
    } else {
      lines.push("");
      lines.push("All cases classified correctly.");
    }
    lines.push("");
  }

  const outDir = path.join(process.cwd(), "reports");
  mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, "external-benchmark.md");
  writeFileSync(outPath, lines.join("\n"), "utf8");

   
  console.log(lines.join("\n"));
   
  console.log(`\nReport written to ${path.relative(process.cwd(), outPath)}`);
}

main().catch((error) => {
   
  console.error(error);
  process.exit(1);
});
