apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cyberrakshak.fullname" . }}-config
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  VECTOR_PROVIDER: {{ .Values.env.VECTOR_PROVIDER | quote }}
