apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cyberrakshak.fullname" . }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | quote }}
  NEXTAUTH_URL: {{ .Values.secrets.NEXTAUTH_URL | quote }}
  API_KEY_PEPPER: {{ .Values.secrets.API_KEY_PEPPER | quote }}
  SCIM_TOKEN_PEPPER: {{ .Values.secrets.SCIM_TOKEN_PEPPER | quote }}
  WEBHOOK_SECRET_PEPPER: {{ .Values.secrets.WEBHOOK_SECRET_PEPPER | quote }}
  REPORT_SIGNING_SECRET: {{ .Values.secrets.REPORT_SIGNING_SECRET | quote }}
